// @ts-nocheck
import { Avatar } from '@commercetools-frontend/ui-kit';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  'https://www.figma.com/design/UoqmtHSHwxvEZRcbsM4A3Z/CT-product-design-system?node-id=87%3A17020',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isHighlighted: figma.boolean('Highlighted'),
      size: figma.enum('Size', {
        Small: 's',
        Medium: 'm',
        Large: 'l',
      }),
      color: figma.enum('Color', {
        Accent: 'accent',
        Purple: 'purple',
        Turquoise: 'turquoise',
        Brown: 'brown',
      }),
      icon: figma.instance('Icon'),
    },
    example: (props) => (
      <Avatar
        isHighlighted={props.isHighlighted}
        size={props.size}
        color={props.color}
        icon={props.icon}
      />
    ),
  }
);
