version: 2
updates:
  # Enables security PR generation for all packages, based on yarn.lock alerts.
  - package-ecosystem: "npm"
    directory: "/"
    security-updates-only: true
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      # Change the default separator (/) to a hyphen (-)
      separator: "-"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
      scope: "deps"
      include: "dependency-name"
    allow:
      - dependency-type: "all"
