version: 2
updates:
  # Enables security PR generation for all packages, based on yarn.lock alerts.
  - package-ecosystem: "npm"
    directory: "/"
    pull-request-branch-name:
      # Change the default separator (/) to a hyphen (-)
      separator: "-"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
    allow:
      - dependency-type: "all"
