// @ts-nocheck
import { FlatButton } from '@commercetools-frontend/ui-kit';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FlatButton,
  'https://www.figma.com/design/UoqmtHSHwxvEZRcbsM4A3Z/CT-product-design-system?node-id=202%3A20410',
  {
    props: {
      label: figma.string('Text'),
      icon: figma.instance('Icon'),
      tone: figma.enum('Tone', {
        primary: 'primary',
        critical: 'critical',
        secondary: 'secondary',
        Inverted: 'inverted',
      }),
    },
    example: (props) => (
      <FlatButton label={props.label} tone={props.tone} icon={props.icon} />
    ),
  }
);
