import os from 'os';
import path from 'path';
import shelljs from 'shelljs';
import vfile from 'vfile';
import { GeneratorReadmeOptions } from '../src/types';
import { transformDocument } from '../src';

const tmpFolder = os.tmpdir();
const testPackages = path.join(tmpFolder, 'packages');

const createTestOptions = (): GeneratorReadmeOptions => ({
  packagePath: path.join(testPackages, 'avenger'),
  dryRun: false,
});

beforeAll(() => {
  shelljs.mkdir('-p', testPackages);
  shelljs.cp('-R', path.join(__dirname, 'fixtures/avenger'), testPackages);
});

describe('generate README', () => {
  it('should generate README based on package info', async () => {
    const options = createTestOptions();
    const file = await transformDocument(vfile(), options);
    const content = file.toString();
    expect(content).toMatchInlineSnapshot(`
      "<!-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. -->
      <!-- This file is created by the \`yarn generate-readme\` script. -->

      # Avenger

      ## Description

      Render an Avenger

      ## Installation

      \`\`\`
      yarn add @commercetools-test/avenger
      \`\`\`

      \`\`\`
      npm --save install @commercetools-test/avenger
      \`\`\`

      Additionally install the peer dependencies (if not present)

      \`\`\`
      yarn add react
      \`\`\`

      \`\`\`
      npm --save install react
      \`\`\`

      ## Usage

      \`\`\`jsx
      /* eslint disable */
      import React from 'react';
      import Avenger from '@commercetools-uikit/avenger';

      const Example = () => <Avenger name=\\"Dr. Strange\\" />;

      export default Example;

      \`\`\`

      ## Properties

      | Props | Type | Required | Default | Description |
      | - | - | :-: | - | - |
      | \`name\` | \`string\` | ✅ | | The name of an Avenger. |
      | \`identity\` | \`object\` | | | The real identity of this Avenger, if known. |
      | \`identity.firstName\` | \`string\` | | | |
      | \`identity.lastName\` | \`string\` | | | |
      | \`identity.age\` | \`number\` | | | |
      | \`onClick\` | \`func\` | | | A callback function when the component is clicked. Signature: \`(event) => void\` |
      | \`abilities\` | \`array\` | ✅ | | List the abilities of this Avenger. |
      | \`abilities[].name\` | \`string\` | ✅ | | The name of the ability. |
      | \`abilities[].description\` | \`string\` | | | |
      | \`movies\` | \`array\` | ✅ | | The list of movies where this Avenger appears in. It can either be just the name of the movie or a more detailed information about the movie. |
      | \`movies[]<string>\` | \`string\` | | | The name of the movie. |
      | \`movies[]<shape>\` | \`object\` | | | Detailed information about the movie. |
      | \`movies[]<shape>.title\` | \`string\` | ✅ | | The title of the movie. |
      | \`movies[]<shape>.releaseDate\` | \`string\` | ✅ | | The release date of the movie (ISO). |
      | \`power\` | \`enum\`<br>Possible values:<br>\`1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10\` | | \`1\` | Define the power for this Avenger, from a scale of 1-10. |
      | \`isAlive\` | \`bool\` | ✅ | | |

      ## More information

      This section should come AFTER the \\"Properties\\".
      "
    `);
  });
});
