/*
  THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

  This file is created by the 'scripts/generate-custom-properties.js' script.
  The variables should be updated in 'materials/internals/definition.yaml'.
*/

export default {
  backgroundColorForInput: 'color-surface',
  backgroundColorForInputWhenSelected: 'color-accent-95',
  backgroundColorForInputWhenDisabled: 'color-accent-98',
  backgroundColorForInputWhenHovered: 'color-neutral-90',
  backgroundColorForTag: 'color-neutral-95',
  backgroundColorForTagWarning: 'color-warning-95',
  borderColorForInput: 'color-neutral-60',
  borderColorForInputWhenFocused: 'color-primary',
  borderColorForInputWhenDisabled: 'color-neutral',
  borderColorForInputWhenReadonly: 'color-neutral',
  borderColorForInputWhenError: 'color-error',
  borderColorForInputWhenWarning: 'color-warning',
  borderColorForTag: 'color-neutral-60',
  borderColorForTagWarning: 'color-warning',
  borderColorForTagWhenFocused: 'color-primary',
  borderRadiusForInput: 'border-radius-6',
  borderRadiusForTag: 'border-radius-2',
  fontColorForInput: 'color-solid',
  fontColorForInputWhenDisabled: 'color-neutral-60',
  fontColorForInputWhenError: 'color-error',
  fontColorForInputWhenReadonly: 'color-neutral-60',
  fontColorForInputWhenWarning: 'color-warning',
  fontColorForTag: 'color-solid',
  fontColorForTagWhenDisabled: 'color-neutral-60',
  fontColorForTextWhenInverted: 'color-surface',
  fontFamily: 'font-family-body',
  placeholderFontColorForInput: 'color-neutral-60',
  fontSizeForInput: 'font-size-m',
  shadowBoxTagWhenHovered: 'shadow-1',
} as const;
