// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file is created with 'yarn generate-icons'.
// Original SVG file: src/svg/heart.react.svg

/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react';
import PropTypes from 'prop-types';
import invariant from 'tiny-invariant';
import { css, useTheme } from '@emotion/react';
import { customProperties as vars } from '@commercetools-uikit/design-system';
const iconSizes = {
  small: 12,
  medium: 16,
  big: 24,
};

const getSizeStyle = (size) => {
  switch (size) {
    case 'scale':
      return `
        &:not(:root) {
          width: 100%;
          height: auto;
        }
      `;

    case 'small':
    case 'medium':
    case 'big':
      return `
        width: ${iconSizes[size]}px;
        height: ${iconSizes[size]}px;
      `;

    default:
      return `
        width: ${iconSizes.big}px;
        height: ${iconSizes.big}px;
      `;
  }
};

const capitalize = (s) => s[0].toUpperCase() + s.slice(1);

const getColor = (color, theme) => {
  if (!color) return 'inherit';
  const overwrittenVars = { ...vars, ...theme };
  const iconColor = overwrittenVars[`color${capitalize(color)}`];

  if (!iconColor) {
    invariant(
      color,
      `ui-kit/Icon: the specified color '${color}' is not supported.`
    );
    return 'inherit';
  }

  return iconColor;
};

const getIconStyles = (props, theme) => css`
  * {
    fill: ${getColor(props.color, theme)};
  }
  ${getSizeStyle(props.size)};
  flex-shrink: 0;
`;

const iconPropTypes = {
  color: PropTypes.oneOf([
    'solid',
    'neutral60',
    'surface',
    'info',
    'primary',
    'primary40',
    'warning',
    'error',
  ]),
  size: PropTypes.oneOf(['small', 'medium', 'big', 'scale']),
};

const SvgHeartreact = (props) => (
  <svg
    id="heart_react_svg__Ebene_1"
    xmlns="http://www.w3.org/2000/svg"
    x={0}
    y={0}
    viewBox="0 0 24 24"
    xmlSpace="preserve"
    width="1em"
    height="1em"
    {...props}
  >
    <g id="heart_react_svg__MC-icon-set" transform="translate(-241 -1256)">
      <g id="heart_react_svg__Heart" transform="translate(241 1256)">
        <path
          id="heart_react_svg__shape"
          className="heart_react_svg__st0"
          d="M16 3.7c-1.7 0-3.3.9-4.1 2.4-.9-1.5-2.4-2.4-4-2.4-2.5 0-4.6 2.1-4.8 5 0 .1-.1.8.2 1.9.4 1.6 1.2 3 2.5 4.1l6.2 5.7 6.3-5.7c1.2-1.1 2.1-2.6 2.5-4.1.3-1.1.2-1.8.2-1.9-.4-3-2.5-5-5-5z"
        />
      </g>
    </g>
  </svg>
);

SvgHeartreact.displayName = 'SvgHeartreact';

const Component = (props) => {
  const theme = useTheme();
  return <SvgHeartreact {...props} css={getIconStyles(props, theme)} />;
};

Component.propTypes = iconPropTypes;
export default Component;
