// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file is created with 'yarn generate-icons'.
// Original SVG file: src/svg/logout.react.svg

/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react';
import PropTypes from 'prop-types';
import invariant from 'tiny-invariant';
import { css, useTheme } from '@emotion/react';
import { customProperties as vars } from '@commercetools-uikit/design-system';
const iconSizes = {
  small: 12,
  medium: 16,
  big: 24,
};

const getSizeStyle = (size) => {
  switch (size) {
    case 'scale':
      return `
        &:not(:root) {
          width: 100%;
          height: auto;
        }
      `;

    case 'small':
    case 'medium':
    case 'big':
      return `
        width: ${iconSizes[size]}px;
        height: ${iconSizes[size]}px;
      `;

    default:
      return `
        width: ${iconSizes.big}px;
        height: ${iconSizes.big}px;
      `;
  }
};

const capitalize = (s) => s[0].toUpperCase() + s.slice(1);

const getColor = (color, theme) => {
  if (!color) return 'inherit';
  const overwrittenVars = { ...vars, ...theme };
  const iconColor = overwrittenVars[`color${capitalize(color)}`];

  if (!iconColor) {
    invariant(
      color,
      `ui-kit/Icon: the specified color '${color}' is not supported.`
    );
    return 'inherit';
  }

  return iconColor;
};

const getIconStyles = (props, theme) => css`
  * {
    fill: ${getColor(props.color, theme)};
  }
  ${getSizeStyle(props.size)};
  flex-shrink: 0;
`;

const iconPropTypes = {
  color: PropTypes.oneOf([
    'solid',
    'neutral60',
    'surface',
    'info',
    'primary',
    'primary40',
    'warning',
    'error',
  ]),
  size: PropTypes.oneOf(['small', 'medium', 'big', 'scale']),
};

const SvgLogoutreact = (props) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <g
      id="logout_react_svg__Icons"
      stroke="none"
      strokeWidth={1}
      fillRule="evenodd"
    >
      <g
        id="logout_react_svg__MC-icon-set"
        transform="translate(-24 -24)"
        fill="#000"
      >
        <g id="logout_react_svg__Application" transform="translate(24 24)">
          <g id="logout_react_svg__Logout">
            <path
              d="M15.763 18.105c-1.358.878-2.953 1.398-4.65 1.398-2.886 0-5.567-1.495-6.993-3.835-1.46-2.373-1.46-5.298-.034-7.703 1.46-2.34 4.107-3.835 6.992-3.835 1.596 0 3.123.455 4.413 1.268l-.883 1.3a7.005 7.005 0 00-3.53-.975c-2.308 0-4.48 1.138-5.6 3.055a5.882 5.882 0 000 6.143c1.12 1.917 3.292 3.055 5.6 3.055 1.358 0 2.614-.39 3.7-1.105l.985 1.234zm4.616-6.24l-3.7-3.478v1.95h-5.906v3.055h5.906v1.983l3.7-3.51z"
              id="logout_react_svg__shape"
            />
          </g>
        </g>
      </g>
    </g>
  </svg>
);

SvgLogoutreact.displayName = 'SvgLogoutreact';

const Component = (props) => {
  const theme = useTheme();
  return <SvgLogoutreact {...props} css={getIconStyles(props, theme)} />;
};

Component.propTypes = iconPropTypes;
export default Component;
