// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file is created with 'yarn generate-icons'.
// Original SVG file: src/svg/paperclip.react.svg

/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react';
import PropTypes from 'prop-types';
import invariant from 'tiny-invariant';
import { css, useTheme } from '@emotion/react';
import { customProperties as vars } from '@commercetools-uikit/design-system';
const iconSizes = {
  small: 12,
  medium: 16,
  big: 24,
};

const getSizeStyle = (size) => {
  switch (size) {
    case 'scale':
      return `
        &:not(:root) {
          width: 100%;
          height: auto;
        }
      `;

    case 'small':
    case 'medium':
    case 'big':
      return `
        width: ${iconSizes[size]}px;
        height: ${iconSizes[size]}px;
      `;

    default:
      return `
        width: ${iconSizes.big}px;
        height: ${iconSizes.big}px;
      `;
  }
};

const capitalize = (s) => s[0].toUpperCase() + s.slice(1);

const getColor = (color, theme) => {
  if (!color) return 'inherit';
  const overwrittenVars = { ...vars, ...theme };
  const iconColor = overwrittenVars[`color${capitalize(color)}`];

  if (!iconColor) {
    invariant(
      color,
      `ui-kit/Icon: the specified color '${color}' is not supported.`
    );
    return 'inherit';
  }

  return iconColor;
};

const getIconStyles = (props, theme) => css`
  * {
    fill: ${getColor(props.color, theme)};
  }
  ${getSizeStyle(props.size)};
  flex-shrink: 0;
`;

const iconPropTypes = {
  color: PropTypes.oneOf([
    'solid',
    'neutral60',
    'surface',
    'info',
    'primary',
    'primary40',
    'warning',
    'error',
  ]),
  size: PropTypes.oneOf(['small', 'medium', 'big', 'scale']),
};

const SvgPaperclipreact = (props) => (
  <svg
    id="paperclip_react_svg__Ebene_1"
    xmlns="http://www.w3.org/2000/svg"
    x={0}
    y={0}
    viewBox="0 0 24 24"
    xmlSpace="preserve"
    width="1em"
    height="1em"
    {...props}
  >
    <g id="paperclip_react_svg__Icons">
      <g id="paperclip_react_svg__MC-icon-set" transform="translate(-24 -1307)">
        <g id="paperclip_react_svg__paperclip" transform="translate(24 1307)">
          <path
            id="paperclip_react_svg__shape"
            d="M9.3 18.7c-.5.5-1.3.8-2.1.8s-1.5-.3-2.1-.8c-.5-.5-.9-1.1-.9-1.8s.3-1.4.9-1.8L16.4 5c.7-.6 1.9-.6 2.6 0 .7.7.7 1.7 0 2.4l-10 9c-.3.3-.8.3-1.1 0-.1-.1-.2-.3-.2-.5s.1-.4.2-.5l5.9-5.1c.2-.1.2-.3.2-.4 0-.2-.1-.3-.2-.4-.3-.2-.7-.2-1 0l-5.9 5.1c-.4.4-.6.8-.6 1.4 0 .5.2 1 .6 1.4.8.7 2.2.7 3 0l10.1-9c.7-.7 1-1.4 1-2.2 0-.8-.3-1.5-.9-2-.6-.5-1.4-.8-2.3-.8-.9 0-1.7.3-2.3.8l-11.2 10c-.9.7-1.3 1.7-1.3 2.7 0 1 .4 2 1.2 2.7.8.7 1.9 1.1 3 1.1s2.2-.4 3-1.1l9.3-8.4c.1-.1.2-.3.2-.4 0-.2-.1-.3-.2-.4-.3-.2-.7-.2-1 0l-9.2 8.3z"
          />
        </g>
      </g>
    </g>
  </svg>
);

SvgPaperclipreact.displayName = 'SvgPaperclipreact';

const Component = (props) => {
  const theme = useTheme();
  return <SvgPaperclipreact {...props} css={getIconStyles(props, theme)} />;
};

Component.propTypes = iconPropTypes;
export default Component;
