// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file is created with 'yarn generate-icons'.
// Original SVG file: src/svg/screen-gear.react.svg

/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react';
import PropTypes from 'prop-types';
import invariant from 'tiny-invariant';
import { css, useTheme } from '@emotion/react';
import { customProperties as vars } from '@commercetools-uikit/design-system';
const iconSizes = {
  small: 12,
  medium: 16,
  big: 24,
};

const getSizeStyle = (size) => {
  switch (size) {
    case 'scale':
      return `
        &:not(:root) {
          width: 100%;
          height: auto;
        }
      `;

    case 'small':
    case 'medium':
    case 'big':
      return `
        width: ${iconSizes[size]}px;
        height: ${iconSizes[size]}px;
      `;

    default:
      return `
        width: ${iconSizes.big}px;
        height: ${iconSizes.big}px;
      `;
  }
};

const capitalize = (s) => s[0].toUpperCase() + s.slice(1);

const getColor = (color, theme) => {
  if (!color) return 'inherit';
  const overwrittenVars = { ...vars, ...theme };
  const iconColor = overwrittenVars[`color${capitalize(color)}`];

  if (!iconColor) {
    invariant(
      color,
      `ui-kit/Icon: the specified color '${color}' is not supported.`
    );
    return 'inherit';
  }

  return iconColor;
};

const getIconStyles = (props, theme) => css`
  * {
    fill: ${getColor(props.color, theme)};
  }
  ${getSizeStyle(props.size)};
  flex-shrink: 0;
`;

const iconPropTypes = {
  color: PropTypes.oneOf([
    'solid',
    'neutral60',
    'surface',
    'info',
    'primary',
    'primary40',
    'warning',
    'error',
  ]),
  size: PropTypes.oneOf(['small', 'medium', 'big', 'scale']),
};

const SvgScreenGearreact = (props) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <g
      id="screen-gear_react_svg__Icons"
      stroke="none"
      strokeWidth={1}
      fillRule="evenodd"
    >
      <g
        id="screen-gear_react_svg__MC-icon-set"
        transform="translate(-24 -552)"
        fill="#000"
      >
        <g id="screen-gear_react_svg__Views" transform="translate(24 552)">
          <g id="screen-gear_react_svg__Screen-Gear">
            <path
              d="M16.51 5.661H5.701v-.9h10.807v.9zM3.9 14.708h2.702v.9H3.901a.9.9 0 01-.901-.9V3.901A.9.9 0 013.9 3h14.41a.9.9 0 01.901.9v3.603h-.9V3.901H3.9v10.807zm15.519.2l1.465 1.114a.335.335 0 01.083.432l-1.389 2.337c-.083.149-.263.21-.423.149l-1.73-.676c-.36.264-.75.493-1.173.662l-.264 1.79a.336.336 0 01-.34.284H12.87a.336.336 0 01-.34-.284l-.264-1.79a5.11 5.11 0 01-1.173-.662l-1.73.676a.354.354 0 01-.423-.149l-1.389-2.337a.335.335 0 01.084-.432L9.1 14.907v-1.324L7.635 12.47a.327.327 0 01-.084-.432l1.39-2.338a.343.343 0 01.423-.148l1.729.675c.36-.263.75-.493 1.173-.662l.264-1.79a.336.336 0 01.34-.283h2.778c.174 0 .32.121.34.283l.264 1.79a5.11 5.11 0 011.174.662l1.729-.675c.153-.054.34 0 .423.148l1.39 2.338a.335.335 0 01-.084.432l-1.465 1.114v1.324zM9.304 7.462H5.702v-.901h3.602v.9zm4.955 9.146c1.34 0 2.43-1.06 2.43-2.364 0-1.303-1.09-2.364-2.43-2.364s-2.43 1.06-2.43 2.364c0 1.304 1.09 2.364 2.43 2.364z"
              id="screen-gear_react_svg__shape"
            />
          </g>
        </g>
      </g>
    </g>
  </svg>
);

SvgScreenGearreact.displayName = 'SvgScreenGearreact';

const Component = (props) => {
  const theme = useTheme();
  return <SvgScreenGearreact {...props} css={getIconStyles(props, theme)} />;
};

Component.propTypes = iconPropTypes;
export default Component;
