// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file is created with 'yarn generate-icons'.
// Original SVG file: src/svg/subdirectory-arrow.react.svg

/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react';
import PropTypes from 'prop-types';
import invariant from 'tiny-invariant';
import { css, useTheme } from '@emotion/react';
import { customProperties as vars } from '@commercetools-uikit/design-system';
const iconSizes = {
  small: 12,
  medium: 16,
  big: 24,
};

const getSizeStyle = (size) => {
  switch (size) {
    case 'scale':
      return `
        &:not(:root) {
          width: 100%;
          height: auto;
        }
      `;

    case 'small':
    case 'medium':
    case 'big':
      return `
        width: ${iconSizes[size]}px;
        height: ${iconSizes[size]}px;
      `;

    default:
      return `
        width: ${iconSizes.big}px;
        height: ${iconSizes.big}px;
      `;
  }
};

const capitalize = (s) => s[0].toUpperCase() + s.slice(1);

const getColor = (color, theme) => {
  if (!color) return 'inherit';
  const overwrittenVars = { ...vars, ...theme };
  const iconColor = overwrittenVars[`color${capitalize(color)}`];

  if (!iconColor) {
    invariant(
      color,
      `ui-kit/Icon: the specified color '${color}' is not supported.`
    );
    return 'inherit';
  }

  return iconColor;
};

const getIconStyles = (props, theme) => css`
  * {
    fill: ${getColor(props.color, theme)};
  }
  ${getSizeStyle(props.size)};
  flex-shrink: 0;
`;

const iconPropTypes = {
  color: PropTypes.oneOf([
    'solid',
    'neutral60',
    'surface',
    'info',
    'primary',
    'primary40',
    'warning',
    'error',
  ]),
  size: PropTypes.oneOf(['small', 'medium', 'big', 'scale']),
};

const SvgSubdirectoryArrowreact = (props) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 11 18"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    {...props}
  >
    <defs>
      <path
        d="M16.404 17v-1.625c0-.102.04-.19.118-.264a.394.394 0 01.28-.111c.107 0 .2.037.279.111l2.78 2.625a.351.351 0 010 .527l-2.78 2.626a.393.393 0 01-.28.111.393.393 0 01-.279-.111.35.35 0 01-.118-.264V19H10a1 1 0 01-1-1V4a1 1 0 112 0v13h5.404z"
        id="subdirectory-arrow_react_svg__path-1"
      />
    </defs>
    <g
      id="subdirectory-arrow_react_svg__Icons"
      stroke="none"
      strokeWidth={1}
      fill="none"
      fillRule="evenodd"
    >
      <g
        id="subdirectory-arrow_react_svg__Component-/-icon-/-12px-/-suplink--"
        transform="translate(-9 -3)"
      >
        <g id="subdirectory-arrow_react_svg__Component-/-icon-/-24px-/-suplink">
          <mask id="subdirectory-arrow_react_svg__mask-2" fill="#fff">
            <use xlinkHref="#subdirectory-arrow_react_svg__path-1" />
          </mask>
          <use
            id="subdirectory-arrow_react_svg__Mask"
            fill="#1A1A1A"
            xlinkHref="#subdirectory-arrow_react_svg__path-1"
          />
        </g>
      </g>
    </g>
  </svg>
);

SvgSubdirectoryArrowreact.displayName = 'SvgSubdirectoryArrowreact';

const Component = (props) => {
  const theme = useTheme();
  return (
    <SvgSubdirectoryArrowreact {...props} css={getIconStyles(props, theme)} />
  );
};

Component.propTypes = iconPropTypes;
export default Component;
