// @ts-nocheck
import { LocalizedRichTextInput } from '@commercetools-frontend/ui-kit';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  LocalizedRichTextInput,
  'https://www.figma.com/design/UoqmtHSHwxvEZRcbsM4A3Z/CT-product-design-system?node-id=893%3A34505',
  {
    props: {
      // display props don't map well to component props, TODO: come back to this when we are more experienced w/code connect
    },
    example: (props) => <LocalizedRichTextInput />,
  }
);
