// This file is auto-generated using the 'generate-icon-exports.js' script
// so any changes made to this file manually will be lost the next time the
// script is executed
import withSizeProp from './with-size-prop';
import withThemeProp from './with-theme-prop';
import OrigAddBoldIcon from './svg/add-bold.svg';
import OrigAddIcon from './svg/add.svg';
import OrigAddressBillingIcon from './svg/address-billing.svg';
import OrigAddressShippingIcon from './svg/address-shipping.svg';
import OrigAngleDownIcon from './svg/angle-down.svg';
import OrigAngleLeftIcon from './svg/angle-left.svg';
import OrigAngleRightIcon from './svg/angle-right.svg';
import OrigAngleUpIcon from './svg/angle-up.svg';
import OrigArrowGraphDownIcon from './svg/arrow-graph-down.svg';
import OrigArrowGraphRightIcon from './svg/arrow-graph-right.svg';
import OrigArrowGraphUpIcon from './svg/arrow-graph-up.svg';
import OrigArrowLeftIcon from './svg/arrow-left.svg';
import OrigArrowLongDownIcon from './svg/arrow-long-down.svg';
import OrigArrowRightIcon from './svg/arrow-right.svg';
import OrigArrowTriangleDownIcon from './svg/arrow-triangle-down.svg';
import OrigArrowTriangleUpIcon from './svg/arrow-triangle-up.svg';
import OrigArrowsIcon from './svg/arrows.svg';
import OrigBackIcon from './svg/back.svg';
import OrigBoxProductIcon from './svg/box-product.svg';
import OrigBoxIcon from './svg/box.svg';
import OrigBrainIcon from './svg/brain.svg';
import OrigCalendarIcon from './svg/calendar.svg';
import OrigCameraIcon from './svg/camera.svg';
import OrigCaretDownIcon from './svg/caret-down.svg';
import OrigCaretUpIcon from './svg/caret-up.svg';
import OrigCartIcon from './svg/cart.svg';
import OrigCategoryTreeIcon from './svg/category-tree.svg';
import OrigChainBrokenIcon from './svg/chain-broken.svg';
import OrigChainIcon from './svg/chain.svg';
import OrigCheckActiveIcon from './svg/check-active.svg';
import OrigCheckInactiveIcon from './svg/check-inactive.svg';
import OrigClockIcon from './svg/clock.svg';
import OrigCloseBoldIcon from './svg/close-bold.svg';
import OrigCloseIcon from './svg/close.svg';
import OrigCodeViewIcon from './svg/code-view.svg';
import OrigCoinsIcon from './svg/coins.svg';
import OrigColumnsIcon from './svg/columns.svg';
import OrigCopyIcon from './svg/copy.svg';
import OrigCubesIcon from './svg/cubes.svg';
import OrigCustomSettingsIcon from './svg/custom-settings.svg';
import OrigCustomViewIcon from './svg/custom-view.svg';
import OrigCustomerFilledIcon from './svg/customer-filled.svg';
import OrigCustomerIcon from './svg/customer.svg';
import OrigDeleteFilledIcon from './svg/delete-filled.svg';
import OrigDeleteIcon from './svg/delete.svg';
import OrigDoneIcon from './svg/done.svg';
import OrigDragDropIcon from './svg/drag-drop.svg';
import OrigDragIcon from './svg/drag.svg';
import OrigEditIcon from './svg/edit.svg';
import OrigErrorIcon from './svg/error.svg';
import OrigExpandIcon from './svg/expand.svg';
import OrigExportIcon from './svg/export.svg';
import OrigFilterIcon from './svg/filter.svg';
import OrigFlagFullfiledIcon from './svg/flag-fullfiled.svg';
import OrigFlagIcon from './svg/flag.svg';
import OrigFlameIcon from './svg/flame.svg';
import OrigGraphIcon from './svg/graph.svg';
import OrigGridIcon from './svg/grid.svg';
import OrigImportIcon from './svg/import.svg';
import OrigInfoIcon from './svg/info.svg';
import OrigInformationIcon from './svg/information.svg';
import OrigListIcon from './svg/list.svg';
import OrigLogoutIcon from './svg/logout.svg';
import OrigMinimizeIcon from './svg/minimize.svg';
import OrigNestedViewIcon from './svg/nested-view.svg';
import OrigPagesIcon from './svg/pages.svg';
import OrigPinActiveIcon from './svg/pin-active.svg';
import OrigPinIcon from './svg/pin.svg';
import OrigRefreshIcon from './svg/refresh.svg';
import OrigRestoreIcon from './svg/restore.svg';
import OrigRevertIcon from './svg/revert.svg';
import OrigSearchIcon from './svg/search.svg';
import OrigSortingIcon from './svg/sorting.svg';
import OrigSpeedometerIcon from './svg/speedometer.svg';
import OrigSplitIcon from './svg/split.svg';
import OrigSuccessIcon from './svg/success.svg';
import OrigSwitcherIcon from './svg/switcher.svg';
import OrigTableIcon from './svg/table.svg';
import OrigTagMultiIcon from './svg/tag-multi.svg';
import OrigTagIcon from './svg/tag.svg';
import OrigVerifiedIcon from './svg/verified.svg';
import OrigWarningIcon from './svg/warning.svg';
import OrigWorldIcon from './svg/world.svg';

const AddBoldIcon = withThemeProp(withSizeProp(OrigAddBoldIcon));
const AddIcon = withThemeProp(withSizeProp(OrigAddIcon));
const AddressBillingIcon = withThemeProp(withSizeProp(OrigAddressBillingIcon));
const AddressShippingIcon = withThemeProp(
  withSizeProp(OrigAddressShippingIcon)
);
const AngleDownIcon = withThemeProp(withSizeProp(OrigAngleDownIcon));
const AngleLeftIcon = withThemeProp(withSizeProp(OrigAngleLeftIcon));
const AngleRightIcon = withThemeProp(withSizeProp(OrigAngleRightIcon));
const AngleUpIcon = withThemeProp(withSizeProp(OrigAngleUpIcon));
const ArrowGraphDownIcon = withThemeProp(withSizeProp(OrigArrowGraphDownIcon));
const ArrowGraphRightIcon = withThemeProp(
  withSizeProp(OrigArrowGraphRightIcon)
);
const ArrowGraphUpIcon = withThemeProp(withSizeProp(OrigArrowGraphUpIcon));
const ArrowLeftIcon = withThemeProp(withSizeProp(OrigArrowLeftIcon));
const ArrowLongDownIcon = withThemeProp(withSizeProp(OrigArrowLongDownIcon));
const ArrowRightIcon = withThemeProp(withSizeProp(OrigArrowRightIcon));
const ArrowTriangleDownIcon = withThemeProp(
  withSizeProp(OrigArrowTriangleDownIcon)
);
const ArrowTriangleUpIcon = withThemeProp(
  withSizeProp(OrigArrowTriangleUpIcon)
);
const ArrowsIcon = withThemeProp(withSizeProp(OrigArrowsIcon));
const BackIcon = withThemeProp(withSizeProp(OrigBackIcon));
const BoxProductIcon = withThemeProp(withSizeProp(OrigBoxProductIcon));
const BoxIcon = withThemeProp(withSizeProp(OrigBoxIcon));
const BrainIcon = withThemeProp(withSizeProp(OrigBrainIcon));
const CalendarIcon = withThemeProp(withSizeProp(OrigCalendarIcon));
const CameraIcon = withThemeProp(withSizeProp(OrigCameraIcon));
const CaretDownIcon = withThemeProp(withSizeProp(OrigCaretDownIcon));
const CaretUpIcon = withThemeProp(withSizeProp(OrigCaretUpIcon));
const CartIcon = withThemeProp(withSizeProp(OrigCartIcon));
const CategoryTreeIcon = withThemeProp(withSizeProp(OrigCategoryTreeIcon));
const ChainBrokenIcon = withThemeProp(withSizeProp(OrigChainBrokenIcon));
const ChainIcon = withThemeProp(withSizeProp(OrigChainIcon));
const CheckActiveIcon = withThemeProp(withSizeProp(OrigCheckActiveIcon));
const CheckInactiveIcon = withThemeProp(withSizeProp(OrigCheckInactiveIcon));
const ClockIcon = withThemeProp(withSizeProp(OrigClockIcon));
const CloseBoldIcon = withThemeProp(withSizeProp(OrigCloseBoldIcon));
const CloseIcon = withThemeProp(withSizeProp(OrigCloseIcon));
const CodeViewIcon = withThemeProp(withSizeProp(OrigCodeViewIcon));
const CoinsIcon = withThemeProp(withSizeProp(OrigCoinsIcon));
const ColumnsIcon = withThemeProp(withSizeProp(OrigColumnsIcon));
const CopyIcon = withThemeProp(withSizeProp(OrigCopyIcon));
const CubesIcon = withThemeProp(withSizeProp(OrigCubesIcon));
const CustomSettingsIcon = withThemeProp(withSizeProp(OrigCustomSettingsIcon));
const CustomViewIcon = withThemeProp(withSizeProp(OrigCustomViewIcon));
const CustomerFilledIcon = withThemeProp(withSizeProp(OrigCustomerFilledIcon));
const CustomerIcon = withThemeProp(withSizeProp(OrigCustomerIcon));
const DeleteFilledIcon = withThemeProp(withSizeProp(OrigDeleteFilledIcon));
const DeleteIcon = withThemeProp(withSizeProp(OrigDeleteIcon));
const DoneIcon = withThemeProp(withSizeProp(OrigDoneIcon));
const DragDropIcon = withThemeProp(withSizeProp(OrigDragDropIcon));
const DragIcon = withThemeProp(withSizeProp(OrigDragIcon));
const EditIcon = withThemeProp(withSizeProp(OrigEditIcon));
const ErrorIcon = withThemeProp(withSizeProp(OrigErrorIcon));
const ExpandIcon = withThemeProp(withSizeProp(OrigExpandIcon));
const ExportIcon = withThemeProp(withSizeProp(OrigExportIcon));
const FilterIcon = withThemeProp(withSizeProp(OrigFilterIcon));
const FlagFullfiledIcon = withThemeProp(withSizeProp(OrigFlagFullfiledIcon));
const FlagIcon = withThemeProp(withSizeProp(OrigFlagIcon));
const FlameIcon = withThemeProp(withSizeProp(OrigFlameIcon));
const GraphIcon = withThemeProp(withSizeProp(OrigGraphIcon));
const GridIcon = withThemeProp(withSizeProp(OrigGridIcon));
const ImportIcon = withThemeProp(withSizeProp(OrigImportIcon));
const InfoIcon = withThemeProp(withSizeProp(OrigInfoIcon));
const InformationIcon = withThemeProp(withSizeProp(OrigInformationIcon));
const ListIcon = withThemeProp(withSizeProp(OrigListIcon));
const LogoutIcon = withThemeProp(withSizeProp(OrigLogoutIcon));
const MinimizeIcon = withThemeProp(withSizeProp(OrigMinimizeIcon));
const NestedViewIcon = withThemeProp(withSizeProp(OrigNestedViewIcon));
const PagesIcon = withThemeProp(withSizeProp(OrigPagesIcon));
const PinActiveIcon = withThemeProp(withSizeProp(OrigPinActiveIcon));
const PinIcon = withThemeProp(withSizeProp(OrigPinIcon));
const RefreshIcon = withThemeProp(withSizeProp(OrigRefreshIcon));
const RestoreIcon = withThemeProp(withSizeProp(OrigRestoreIcon));
const RevertIcon = withThemeProp(withSizeProp(OrigRevertIcon));
const SearchIcon = withThemeProp(withSizeProp(OrigSearchIcon));
const SortingIcon = withThemeProp(withSizeProp(OrigSortingIcon));
const SpeedometerIcon = withThemeProp(withSizeProp(OrigSpeedometerIcon));
const SplitIcon = withThemeProp(withSizeProp(OrigSplitIcon));
const SuccessIcon = withThemeProp(withSizeProp(OrigSuccessIcon));
const SwitcherIcon = withThemeProp(withSizeProp(OrigSwitcherIcon));
const TableIcon = withThemeProp(withSizeProp(OrigTableIcon));
const TagMultiIcon = withThemeProp(withSizeProp(OrigTagMultiIcon));
const TagIcon = withThemeProp(withSizeProp(OrigTagIcon));
const VerifiedIcon = withThemeProp(withSizeProp(OrigVerifiedIcon));
const WarningIcon = withThemeProp(withSizeProp(OrigWarningIcon));
const WorldIcon = withThemeProp(withSizeProp(OrigWorldIcon));

AddBoldIcon.displayName = 'AddBoldIcon';
AddIcon.displayName = 'AddIcon';
AddressBillingIcon.displayName = 'AddressBillingIcon';
AddressShippingIcon.displayName = 'AddressShippingIcon';
AngleDownIcon.displayName = 'AngleDownIcon';
AngleLeftIcon.displayName = 'AngleLeftIcon';
AngleRightIcon.displayName = 'AngleRightIcon';
AngleUpIcon.displayName = 'AngleUpIcon';
ArrowGraphDownIcon.displayName = 'ArrowGraphDownIcon';
ArrowGraphRightIcon.displayName = 'ArrowGraphRightIcon';
ArrowGraphUpIcon.displayName = 'ArrowGraphUpIcon';
ArrowLeftIcon.displayName = 'ArrowLeftIcon';
ArrowLongDownIcon.displayName = 'ArrowLongDownIcon';
ArrowRightIcon.displayName = 'ArrowRightIcon';
ArrowTriangleDownIcon.displayName = 'ArrowTriangleDownIcon';
ArrowTriangleUpIcon.displayName = 'ArrowTriangleUpIcon';
ArrowsIcon.displayName = 'ArrowsIcon';
BackIcon.displayName = 'BackIcon';
BoxProductIcon.displayName = 'BoxProductIcon';
BoxIcon.displayName = 'BoxIcon';
BrainIcon.displayName = 'BrainIcon';
CalendarIcon.displayName = 'CalendarIcon';
CameraIcon.displayName = 'CameraIcon';
CaretDownIcon.displayName = 'CaretDownIcon';
CaretUpIcon.displayName = 'CaretUpIcon';
CartIcon.displayName = 'CartIcon';
CategoryTreeIcon.displayName = 'CategoryTreeIcon';
ChainBrokenIcon.displayName = 'ChainBrokenIcon';
ChainIcon.displayName = 'ChainIcon';
CheckActiveIcon.displayName = 'CheckActiveIcon';
CheckInactiveIcon.displayName = 'CheckInactiveIcon';
ClockIcon.displayName = 'ClockIcon';
CloseBoldIcon.displayName = 'CloseBoldIcon';
CloseIcon.displayName = 'CloseIcon';
CodeViewIcon.displayName = 'CodeViewIcon';
CoinsIcon.displayName = 'CoinsIcon';
ColumnsIcon.displayName = 'ColumnsIcon';
CopyIcon.displayName = 'CopyIcon';
CubesIcon.displayName = 'CubesIcon';
CustomSettingsIcon.displayName = 'CustomSettingsIcon';
CustomViewIcon.displayName = 'CustomViewIcon';
CustomerFilledIcon.displayName = 'CustomerFilledIcon';
CustomerIcon.displayName = 'CustomerIcon';
DeleteFilledIcon.displayName = 'DeleteFilledIcon';
DeleteIcon.displayName = 'DeleteIcon';
DoneIcon.displayName = 'DoneIcon';
DragDropIcon.displayName = 'DragDropIcon';
DragIcon.displayName = 'DragIcon';
EditIcon.displayName = 'EditIcon';
ErrorIcon.displayName = 'ErrorIcon';
ExpandIcon.displayName = 'ExpandIcon';
ExportIcon.displayName = 'ExportIcon';
FilterIcon.displayName = 'FilterIcon';
FlagFullfiledIcon.displayName = 'FlagFullfiledIcon';
FlagIcon.displayName = 'FlagIcon';
FlameIcon.displayName = 'FlameIcon';
GraphIcon.displayName = 'GraphIcon';
GridIcon.displayName = 'GridIcon';
ImportIcon.displayName = 'ImportIcon';
InfoIcon.displayName = 'InfoIcon';
InformationIcon.displayName = 'InformationIcon';
ListIcon.displayName = 'ListIcon';
LogoutIcon.displayName = 'LogoutIcon';
MinimizeIcon.displayName = 'MinimizeIcon';
NestedViewIcon.displayName = 'NestedViewIcon';
PagesIcon.displayName = 'PagesIcon';
PinActiveIcon.displayName = 'PinActiveIcon';
PinIcon.displayName = 'PinIcon';
RefreshIcon.displayName = 'RefreshIcon';
RestoreIcon.displayName = 'RestoreIcon';
RevertIcon.displayName = 'RevertIcon';
SearchIcon.displayName = 'SearchIcon';
SortingIcon.displayName = 'SortingIcon';
SpeedometerIcon.displayName = 'SpeedometerIcon';
SplitIcon.displayName = 'SplitIcon';
SuccessIcon.displayName = 'SuccessIcon';
SwitcherIcon.displayName = 'SwitcherIcon';
TableIcon.displayName = 'TableIcon';
TagMultiIcon.displayName = 'TagMultiIcon';
TagIcon.displayName = 'TagIcon';
VerifiedIcon.displayName = 'VerifiedIcon';
WarningIcon.displayName = 'WarningIcon';
WorldIcon.displayName = 'WorldIcon';

export { AddBoldIcon };
export { AddIcon };
export { AddressBillingIcon };
export { AddressShippingIcon };
export { AngleDownIcon };
export { AngleLeftIcon };
export { AngleRightIcon };
export { AngleUpIcon };
export { ArrowGraphDownIcon };
export { ArrowGraphRightIcon };
export { ArrowGraphUpIcon };
export { ArrowLeftIcon };
export { ArrowLongDownIcon };
export { ArrowRightIcon };
export { ArrowTriangleDownIcon };
export { ArrowTriangleUpIcon };
export { ArrowsIcon };
export { BackIcon };
export { BoxProductIcon };
export { BoxIcon };
export { BrainIcon };
export { CalendarIcon };
export { CameraIcon };
export { CaretDownIcon };
export { CaretUpIcon };
export { CartIcon };
export { CategoryTreeIcon };
export { ChainBrokenIcon };
export { ChainIcon };
export { CheckActiveIcon };
export { CheckInactiveIcon };
export { ClockIcon };
export { CloseBoldIcon };
export { CloseIcon };
export { CodeViewIcon };
export { CoinsIcon };
export { ColumnsIcon };
export { CopyIcon };
export { CubesIcon };
export { CustomSettingsIcon };
export { CustomViewIcon };
export { CustomerFilledIcon };
export { CustomerIcon };
export { DeleteFilledIcon };
export { DeleteIcon };
export { DoneIcon };
export { DragDropIcon };
export { DragIcon };
export { EditIcon };
export { ErrorIcon };
export { ExpandIcon };
export { ExportIcon };
export { FilterIcon };
export { FlagFullfiledIcon };
export { FlagIcon };
export { FlameIcon };
export { GraphIcon };
export { GridIcon };
export { ImportIcon };
export { InfoIcon };
export { InformationIcon };
export { ListIcon };
export { LogoutIcon };
export { MinimizeIcon };
export { NestedViewIcon };
export { PagesIcon };
export { PinActiveIcon };
export { PinIcon };
export { RefreshIcon };
export { RestoreIcon };
export { RevertIcon };
export { SearchIcon };
export { SortingIcon };
export { SpeedometerIcon };
export { SplitIcon };
export { SuccessIcon };
export { SwitcherIcon };
export { TableIcon };
export { TagMultiIcon };
export { TagIcon };
export { VerifiedIcon };
export { WarningIcon };
export { WorldIcon };
