// @ts-nocheck
import { SecondaryIconButton } from '@commercetools-frontend/ui-kit';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SecondaryIconButton,
  'https://www.figma.com/design/UoqmtHSHwxvEZRcbsM4A3Z/CT-product-design-system?node-id=1301%3A39256',
  {
    props: {
      // TODO: Add props here
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled"
      // }),
      // "size": figma.enum('Size', {
      //   "40": "40",
      //   "30": "30",
      //   "20": "20",
      //   "10": "10"
      // }),
      // "color": figma.enum('Color', {
      //   "Solid": "solid",
      //   "Primary": "primary",
      //   "Info": "info"
      // })
      children: figma.children('*'),
    },
    example: (props) => (
      <SecondaryIconButton>{props.children}</SecondaryIconButton>
    ),
  }
);
