// @ts-nocheck
import SecondaryButton from './secondary-button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SecondaryButton,
  'https://www.figma.com/design/UoqmtHSHwxvEZRcbsM4A3Z/CT-product-design-system?node-id=86%3A17112',
  {
    props: {
      // TODO: Add props here
      // No matching props could be found for these Figma properties:
      // "rightIcon": figma.instance('↳ right icon'),
      // "rightIcon": figma.boolean('Right icon'),
      // "text": figma.string('Text'),
      // "leftIcon": figma.instance('↳ left icon'),
      // "leftIcon": figma.boolean('Left icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Toggled": "toggled",
      //   "Disabled": "disabled"
      // }),
      // "size": figma.enum('Size', {
      //   "Big": "big",
      //   "Medium": "medium"
      // }),
      // "tone": figma.enum('Tone', {
      //   "Default": "default",
      //   "Info": "info"
      // })
    },
    example: (props) => <SecondaryButton />,
  }
);
