/*
  THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  This file is created by the 'scripts/generate-custom-properties.js' script.
  The variables should be updated in 'materials/internals/definition.yaml'.
*/
export const themes = {
  default: {
    colorPrimary: '#00b39e',
    colorPrimary25: 'hsl(172.9608938547486, 100%, 25%)',
    colorPrimary40: 'hsl(172.9608938547486, 100%, 40%)',
    colorPrimary85: 'hsl(172.9608938547486, 100%, 85%)',
    colorPrimary95: 'hsl(172.9608938547486, 100%, 95%)',
    colorAccent: '#213c45',
    colorAccent30: 'hsl(195, 35.2941176471%, 30%)',
    colorAccent40: 'hsl(195, 35.2941176471%, 40%)',
    colorAccent95: 'hsl(195, 35.2941176471%, 95%)',
    colorAccent98: 'hsl(195, 35.2941176471%, 98%)',
    colorNeutral: '#ccc',
    colorNeutral60: 'hsl(0, 0%, 60%)',
    colorNeutral90: 'hsl(0, 0%, 90%)',
    colorNeutral95: 'hsl(0, 0%, 95%)',
    colorInfo: '#078cdf',
    colorInfo85: 'hsl(203.05555555555554, 93.9130434783%, 85%)',
    colorInfo95: 'hsl(203.05555555555554, 93.9130434783%, 95%)',
    colorWarning: '#f16d0e',
    colorWarning95: 'hsl(25.110132158590307, 89.0196078431%, 95%)',
    colorError: '#e60050',
    colorError95: 'hsl(339.1304347826087, 100%, 95%)',
    colorSolid: '#1a1a1a',
    colorSurface: '#fff',
    borderRadius1: '1px',
    borderRadius2: '2px',
    borderRadius4: '4px',
    borderRadius6: '6px',
    borderRadius20: '20px',
    fontFamilyBody: "'Open Sans', sans-serif",
    fontSizeM: '1rem',
    shadow1: '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    shadow2: '0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)',
    shadow3: '0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23)',
    shadow4: '0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22)',
    shadow5: '0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)',
    shadow6: '0 -1px 2px 0 rgba(0, 0, 0, 0.2)',
    shadow7:
      '0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24)',
    shadow8:
      '0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24)',
    shadow9:
      'inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25)',
    shadow10: '0 0 0 1px rgba(224, 230, 237, 0.5)',
    shadow11:
      '0 1px 0.5px rgba(0, 0, 0, 0.24), 0 -1px 0.75px rgba(0, 0, 0, 0.12)',
    shadow12: '0 0 1px rgba(0, 0, 0, 0.25)',
    shadow13: '0 0 1px rgba(0, 0, 0, 0.25)',
    shadow14: '0 0 0.5px rgba(0, 0, 0, 0.1)',
    shadow15: '0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12)',
    shadow16:
      '0.5px 1.5px 4px 1px rgba(0, 0, 0, 0.25), -0.5px -0.5px 4px 1px rgba(0, 0, 0, 0.25)',
    constraintScale: '100%',
    constraint1: '42px',
    constraint2: '84px',
    constraint3: '142px',
    constraint4: '184px',
    constraint5: '242px',
    constraint6: '284px',
    constraint7: '342px',
    constraint8: '384px',
    constraint9: '442px',
    constraint10: '484px',
    constraint11: '542px',
    constraint12: '584px',
    constraint13: '642px',
    constraint14: '684px',
    constraint15: '742px',
    constraint16: '784px',
    spacingXs: '4px',
    spacingS: '8px',
    spacingM: '16px',
    spacingL: '24px',
    spacingXl: '32px',
    transitionLinear80Ms: '80ms linear',
    transitionEaseinout150Ms: '150ms ease-in-out',
    transitionStandard: '200ms ease',
    breakPointMobile: '768px',
    breakPointDesktop: '1024px',
    breakPointBiggerdesktop: '1280px',
    breakPointGiantdesktop: '1680px',
    breakPointJumbodesktop: '1920px',
    backgroundColorForInput: '#fff',
    backgroundColorForInputWhenSelected: 'hsl(195, 35.2941176471%, 95%)',
    backgroundColorForInputWhenDisabled: 'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForInputWhenHovered: 'hsl(0, 0%, 90%)',
    backgroundColorForTag: 'hsl(0, 0%, 95%)',
    backgroundColorForTagWarning:
      'hsl(25.110132158590307, 89.0196078431%, 95%)',
    borderColorForInput: 'hsl(0, 0%, 60%)',
    borderColorForInputWhenFocused: '#00b39e',
    borderColorForInputWhenDisabled: '#ccc',
    borderColorForInputWhenReadonly: '#ccc',
    borderColorForInputWhenError: '#e60050',
    borderColorForInputWhenWarning: '#f16d0e',
    borderColorForTag: 'hsl(0, 0%, 60%)',
    borderColorForTagWarning: '#f16d0e',
    borderColorForTagWhenFocused: '#00b39e',
    borderRadiusForInput: '6px',
    borderRadiusForTag: '2px',
    fontColorForInput: '#1a1a1a',
    fontColorForInputWhenDisabled: 'hsl(0, 0%, 60%)',
    fontColorForInputWhenError: '#e60050',
    fontColorForInputWhenReadonly: 'hsl(0, 0%, 60%)',
    fontColorForInputWhenWarning: '#f16d0e',
    fontColorForTag: '#1a1a1a',
    fontColorForTagWhenDisabled: 'hsl(0, 0%, 60%)',
    fontColorForTextWhenInverted: '#fff',
    fontFamily: "'Open Sans', sans-serif",
    placeholderFontColorForInput: 'hsl(0, 0%, 60%)',
    fontSizeForInput: '1rem',
    shadowBoxTagWhenHovered:
      '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    bigButtonHeight: '32px',
    smallButtonHeight: '24px',
    sizeHeightInput: '32px',
    fontFamilyDefault: "'Open Sans', sans-serif",
    fontSizeDefault: '1rem',
    fontSizeSmall: '0.9231rem',
    shadowBoxTagHover:
      '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    sizeHeightTag: '26px',
    standardInputHeight: '32px',
  },
  dark: {
    colorPrimary: '#f78d26',
    colorSolid: '#fff',
    colorSurface: '#1a1a1a',
  },
} as const;

export const themesNames = {
  default: 'default',
  dark: 'dark',
} as const;

const customProperties = {
  colorPrimary: 'var(--color-primary, #00b39e)',
  colorPrimary25: 'var(--color-primary-25, hsl(172.9608938547486, 100%, 25%))',
  colorPrimary40: 'var(--color-primary-40, hsl(172.9608938547486, 100%, 40%))',
  colorPrimary85: 'var(--color-primary-85, hsl(172.9608938547486, 100%, 85%))',
  colorPrimary95: 'var(--color-primary-95, hsl(172.9608938547486, 100%, 95%))',
  colorAccent: 'var(--color-accent, #213c45)',
  colorAccent30: 'var(--color-accent-30, hsl(195, 35.2941176471%, 30%))',
  colorAccent40: 'var(--color-accent-40, hsl(195, 35.2941176471%, 40%))',
  colorAccent95: 'var(--color-accent-95, hsl(195, 35.2941176471%, 95%))',
  colorAccent98: 'var(--color-accent-98, hsl(195, 35.2941176471%, 98%))',
  colorNeutral: 'var(--color-neutral, #ccc)',
  colorNeutral60: 'var(--color-neutral-60, hsl(0, 0%, 60%))',
  colorNeutral90: 'var(--color-neutral-90, hsl(0, 0%, 90%))',
  colorNeutral95: 'var(--color-neutral-95, hsl(0, 0%, 95%))',
  colorInfo: 'var(--color-info, #078cdf)',
  colorInfo85:
    'var(--color-info-85, hsl(203.05555555555554, 93.9130434783%, 85%))',
  colorInfo95:
    'var(--color-info-95, hsl(203.05555555555554, 93.9130434783%, 95%))',
  colorWarning: 'var(--color-warning, #f16d0e)',
  colorWarning95:
    'var(--color-warning-95, hsl(25.110132158590307, 89.0196078431%, 95%))',
  colorError: 'var(--color-error, #e60050)',
  colorError95: 'var(--color-error-95, hsl(339.1304347826087, 100%, 95%))',
  colorSolid: 'var(--color-solid, #1a1a1a)',
  colorSurface: 'var(--color-surface, #fff)',
  borderRadius1: 'var(--border-radius-1, 1px)',
  borderRadius2: 'var(--border-radius-2, 2px)',
  borderRadius4: 'var(--border-radius-4, 4px)',
  borderRadius6: 'var(--border-radius-6, 6px)',
  borderRadius20: 'var(--border-radius-20, 20px)',
  fontFamilyBody: "var(--font-family-body, 'Open Sans', sans-serif)",
  fontSizeM: 'var(--font-size-m, 1rem)',
  shadow1:
    'var(--shadow-1, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  shadow2:
    'var(--shadow-2, 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23))',
  shadow3:
    'var(--shadow-3, 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23))',
  shadow4:
    'var(--shadow-4, 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22))',
  shadow5:
    'var(--shadow-5, 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22))',
  shadow6: 'var(--shadow-6, 0 -1px 2px 0 rgba(0, 0, 0, 0.2))',
  shadow7:
    'var(--shadow-7, 0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24))',
  shadow8:
    'var(--shadow-8, 0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24))',
  shadow9:
    'var(--shadow-9, inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25))',
  shadow10: 'var(--shadow-10, 0 0 0 1px rgba(224, 230, 237, 0.5))',
  shadow11:
    'var(--shadow-11, 0 1px 0.5px rgba(0, 0, 0, 0.24), 0 -1px 0.75px rgba(0, 0, 0, 0.12))',
  shadow12: 'var(--shadow-12, 0 0 1px rgba(0, 0, 0, 0.25))',
  shadow13: 'var(--shadow-13, 0 0 1px rgba(0, 0, 0, 0.25))',
  shadow14: 'var(--shadow-14, 0 0 0.5px rgba(0, 0, 0, 0.1))',
  shadow15:
    'var(--shadow-15, 0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12))',
  shadow16:
    'var(--shadow-16, 0.5px 1.5px 4px 1px rgba(0, 0, 0, 0.25), -0.5px -0.5px 4px 1px rgba(0, 0, 0, 0.25))',
  constraintScale: 'var(--constraint-scale, 100%)',
  constraint1: 'var(--constraint-1, 42px)',
  constraint2: 'var(--constraint-2, 84px)',
  constraint3: 'var(--constraint-3, 142px)',
  constraint4: 'var(--constraint-4, 184px)',
  constraint5: 'var(--constraint-5, 242px)',
  constraint6: 'var(--constraint-6, 284px)',
  constraint7: 'var(--constraint-7, 342px)',
  constraint8: 'var(--constraint-8, 384px)',
  constraint9: 'var(--constraint-9, 442px)',
  constraint10: 'var(--constraint-10, 484px)',
  constraint11: 'var(--constraint-11, 542px)',
  constraint12: 'var(--constraint-12, 584px)',
  constraint13: 'var(--constraint-13, 642px)',
  constraint14: 'var(--constraint-14, 684px)',
  constraint15: 'var(--constraint-15, 742px)',
  constraint16: 'var(--constraint-16, 784px)',
  spacingXs: 'var(--spacing-xs, 4px)',
  spacingS: 'var(--spacing-s, 8px)',
  spacingM: 'var(--spacing-m, 16px)',
  spacingL: 'var(--spacing-l, 24px)',
  spacingXl: 'var(--spacing-xl, 32px)',
  transitionLinear80Ms: 'var(--transition-linear-80-ms, 80ms linear)',
  transitionEaseinout150Ms:
    'var(--transition-easeinout-150-ms, 150ms ease-in-out)',
  transitionStandard: 'var(--transition-standard, 200ms ease)',
  breakPointMobile: 'var(--break-point-mobile, 768px)',
  breakPointDesktop: 'var(--break-point-desktop, 1024px)',
  breakPointBiggerdesktop: 'var(--break-point-biggerdesktop, 1280px)',
  breakPointGiantdesktop: 'var(--break-point-giantdesktop, 1680px)',
  breakPointJumbodesktop: 'var(--break-point-jumbodesktop, 1920px)',
  backgroundColorForInput: 'var(--background-color-for-input, #fff)',
  backgroundColorForInputWhenSelected:
    'var(--background-color-for-input-when-selected, hsl(195, 35.2941176471%, 95%))',
  backgroundColorForInputWhenDisabled:
    'var(--background-color-for-input-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForInputWhenHovered:
    'var(--background-color-for-input-when-hovered, hsl(0, 0%, 90%))',
  backgroundColorForTag: 'var(--background-color-for-tag, hsl(0, 0%, 95%))',
  backgroundColorForTagWarning:
    'var(--background-color-for-tag-warning, hsl(25.110132158590307, 89.0196078431%, 95%))',
  borderColorForInput: 'var(--border-color-for-input, hsl(0, 0%, 60%))',
  borderColorForInputWhenFocused:
    'var(--border-color-for-input-when-focused, #00b39e)',
  borderColorForInputWhenDisabled:
    'var(--border-color-for-input-when-disabled, #ccc)',
  borderColorForInputWhenReadonly:
    'var(--border-color-for-input-when-readonly, #ccc)',
  borderColorForInputWhenError:
    'var(--border-color-for-input-when-error, #e60050)',
  borderColorForInputWhenWarning:
    'var(--border-color-for-input-when-warning, #f16d0e)',
  borderColorForTag: 'var(--border-color-for-tag, hsl(0, 0%, 60%))',
  borderColorForTagWarning: 'var(--border-color-for-tag-warning, #f16d0e)',
  borderColorForTagWhenFocused:
    'var(--border-color-for-tag-when-focused, #00b39e)',
  borderRadiusForInput: 'var(--border-radius-for-input, 6px)',
  borderRadiusForTag: 'var(--border-radius-for-tag, 2px)',
  fontColorForInput: 'var(--font-color-for-input, #1a1a1a)',
  fontColorForInputWhenDisabled:
    'var(--font-color-for-input-when-disabled, hsl(0, 0%, 60%))',
  fontColorForInputWhenError: 'var(--font-color-for-input-when-error, #e60050)',
  fontColorForInputWhenReadonly:
    'var(--font-color-for-input-when-readonly, hsl(0, 0%, 60%))',
  fontColorForInputWhenWarning:
    'var(--font-color-for-input-when-warning, #f16d0e)',
  fontColorForTag: 'var(--font-color-for-tag, #1a1a1a)',
  fontColorForTagWhenDisabled:
    'var(--font-color-for-tag-when-disabled, hsl(0, 0%, 60%))',
  fontColorForTextWhenInverted:
    'var(--font-color-for-text-when-inverted, #fff)',
  fontFamily: "var(--font-family, 'Open Sans', sans-serif)",
  placeholderFontColorForInput:
    'var(--placeholder-font-color-for-input, hsl(0, 0%, 60%))',
  fontSizeForInput: 'var(--font-size-for-input, 1rem)',
  shadowBoxTagWhenHovered:
    'var(--shadow-box-tag-when-hovered, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  bigButtonHeight: 'var(--big-button-height, 32px)',
  smallButtonHeight: 'var(--small-button-height, 24px)',
  sizeHeightInput: 'var(--size-height-input, 32px)',
  fontFamilyDefault: "var(--font-family-default, 'Open Sans', sans-serif)",
  fontSizeDefault: 'var(--font-size-default, 1rem)',
  fontSizeSmall: 'var(--font-size-small, 0.9231rem)',
  shadowBoxTagHover:
    'var(--shadow-box-tag-hover, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  sizeHeightTag: 'var(--size-height-tag, 26px)',
  standardInputHeight: 'var(--standard-input-height, 32px)',
} as const;

export default customProperties;
