/*
  THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  This file is created by the 'scripts/generate-design-tokens.js' script.
  The variables should be updated in 'materials/internals/definition.yaml'.
*/
export const themes = {
  default: {
    colorPrimary: '#00b39e',
    colorPrimary25: 'hsl(172.9608938547486, 100%, 25%)',
    colorPrimary40: 'hsl(172.9608938547486, 100%, 40%)',
    colorPrimary85: 'hsl(172.9608938547486, 100%, 85%)',
    colorPrimary95: 'hsl(172.9608938547486, 100%, 95%)',
    colorAccent: '#213c45',
    colorAccent10: 'hsl(195, 35.2941176471%, 10%)',
    colorAccent20: 'hsl(195, 35.2941176471%, 20%)',
    colorAccent30: 'hsl(195, 35.2941176471%, 30%)',
    colorAccent40: 'hsl(195, 35.2941176471%, 40%)',
    colorAccent90: 'hsl(195, 35.2941176471%, 90%)',
    colorAccent95: 'hsl(195, 35.2941176471%, 95%)',
    colorAccent98: 'hsl(195, 35.2941176471%, 98%)',
    colorNeutral: '#ccc',
    colorNeutral05: 'hsl(0deg 0% 80% / 5%)',
    colorNeutral10: 'hsl(0deg 0% 80% / 10%)',
    colorNeutral40: 'hsl(0, 0%, 40%)',
    colorNeutral60: 'hsl(0, 0%, 60%)',
    colorNeutral85: 'hsl(0, 0%, 85%)',
    colorNeutral90: 'hsl(0, 0%, 90%)',
    colorNeutral95: 'hsl(0, 0%, 95%)',
    colorNeutral98: 'hsl(0, 0%, 98%)',
    colorInfo: '#078cdf',
    colorInfo40: 'hsl(203.05555555555554, 93.9130434783%, 40%)',
    colorInfo85: 'hsl(203.05555555555554, 93.9130434783%, 85%)',
    colorInfo95: 'hsl(203.05555555555554, 93.9130434783%, 95%)',
    colorWarning: '#f16d0e',
    colorWarning25: 'hsl(25.110132158590307, 89.0196078431%, 25%)',
    colorWarning40: 'hsl(25.110132158590307, 89.0196078431%, 40%)',
    colorWarning85: 'hsl(25.110132158590307, 89.0196078431%, 85%)',
    colorWarning95: 'hsl(25.110132158590307, 89.0196078431%, 95%)',
    colorError: '#e60050',
    colorError25: 'hsl(339.1304347826087, 100%, 25%)',
    colorError40: 'hsl(339.1304347826087, 100%, 40%)',
    colorError85: 'hsl(339.1304347826087, 100%, 85%)',
    colorError95: 'hsl(339.1304347826087, 100%, 95%)',
    colorSolid: '#1a1a1a',
    colorSolid05: 'hsl(0deg 0% 10% / 5%)',
    colorSolid10: 'hsl(0deg 0% 10% / 10%)',
    colorSurface: '#fff',
    borderRadius1: '1px',
    borderRadius2: '2px',
    borderRadius4: '4px',
    borderRadius6: '6px',
    borderRadius20: '20px',
    borderWidth1: '1px',
    borderWidth2: '2px',
    fontFamily: "'Open Sans', sans-serif",
    fontSize10: '0.75rem',
    fontSize20: '0.875rem',
    fontSize30: '1rem',
    fontSize40: '1.125rem',
    fontSize50: '1.25rem',
    fontSize60: '1.5rem',
    fontSize70: '2rem',
    fontSize80: '2.5rem',
    fontSize15: '0.9231rem',
    fontSize35: '1.0769rem',
    fontSize45: '1.2308rem',
    fontSize63: '1.5385rem',
    fontSize66: '1.8462rem',
    fontSize69: '2.4615rem',
    fontSize78: '3rem',
    fontWeight300: '300',
    fontWeight400: '400',
    fontWeight500: '500',
    fontWeight600: '600',
    fontWeight700: '700',
    lineHeight10: '1.25rem',
    lineHeight20: '1.375rem',
    lineHeight30: '1.5rem',
    lineHeight40: '1.625rem',
    lineHeight50: '1.75rem',
    lineHeight60: '2.125rem',
    shadow0: 'none',
    shadow1: '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    shadow2: '0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)',
    shadow3: '0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23)',
    shadow4: '0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22)',
    shadow5: '0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)',
    shadow6: '0 -1px 2px 0 rgba(0, 0, 0, 0.2)',
    shadow7:
      '0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24)',
    shadow8:
      '0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24)',
    shadow9:
      'inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25)',
    shadow10: '0 0 0 1px rgba(224, 230, 237, 0.5)',
    shadow11:
      '0 1px 0.5px rgba(0, 0, 0, 0.24), 0 -1px 0.75px rgba(0, 0, 0, 0.12)',
    shadow12: '0 0 1px rgba(0, 0, 0, 0.25)',
    shadow13: '0 0 1px rgba(0, 0, 0, 0.25)',
    shadow14: '0 0 0.5px rgba(0, 0, 0, 0.1)',
    shadow15: '0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12)',
    shadow16:
      '0.5px 1.5px 4px 1px rgba(0, 0, 0, 0.25), -0.5px -0.5px 4px 1px rgba(0, 0, 0, 0.25)',
    constraintScale: '100%',
    constraint1: '42px',
    constraint2: '84px',
    constraint3: '142px',
    constraint4: '184px',
    constraint5: '242px',
    constraint6: '284px',
    constraint7: '342px',
    constraint8: '384px',
    constraint9: '442px',
    constraint10: '484px',
    constraint11: '542px',
    constraint12: '584px',
    constraint13: '642px',
    constraint14: '684px',
    constraint15: '742px',
    constraint16: '784px',
    spacingXs: '4px',
    spacingS: '8px',
    spacingM: '16px',
    spacingL: '24px',
    spacingXl: '32px',
    spacing10: '4px',
    spacing20: '8px',
    spacing30: '16px',
    spacing40: '24px',
    spacing50: '32px',
    spacing60: '48px',
    spacing70: '64px',
    transitionLinear80Ms: '80ms linear',
    transitionEaseinout150Ms: '150ms ease-in-out',
    transitionStandard: '200ms ease',
    breakPointMobile: '768px',
    breakPointDesktop: '1024px',
    breakPointBiggerdesktop: '1280px',
    breakPointGiantdesktop: '1680px',
    breakPointJumbodesktop: '1920px',
    backgroundColorForButtonWhenActive: '#fff',
    backgroundColorForButtonWhenHovered: '#fff',
    backgroundColorForButtonAsPrimaryWhenActive: '#00b39e',
    backgroundColorForButtonAsPrimaryWhenHovered:
      'hsl(172.9608938547486, 100%, 25%)',
    backgroundColorForButtonAsIconAsPrimaryWhenActive: '#00b39e',
    backgroundColorForButtonAsIconAsPrimaryWhenHovered: '#00b39e',
    backgroundColorForButtonAsIconAsInfoWhenActive: '#078cdf',
    backgroundColorForButtonAsIconAsInfoWhenHovered: '#078cdf',
    backgroundColorForButtonAsUrgentWhenActive: '#f16d0e',
    backgroundColorForButtonAsUrgentWhenHovered:
      'hsl(25.110132158590307, 89.0196078431%, 25%)',
    backgroundColorForButtonWhenDisabled: 'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForInput: '#fff',
    backgroundColorForInputWhenSelected: 'hsl(195, 35.2941176471%, 95%)',
    backgroundColorForInputWhenDisabled: 'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForInputWhenHovered: '#fff',
    backgroundColorForInputWhenFocused: '#fff',
    backgroundColorForInputWhenReadonly: '#fff',
    backgroundColorForInputWhenActive: 'hsl(195, 35.2941176471%, 95%)',
    backgroundColorForTableCellWhenHovered: 'hsl(0, 0%, 90%)',
    backgroundColorForTableHeader: '#213c45',
    backgroundColorForTag: 'hsl(0, 0%, 95%)',
    backgroundColorForTagWarning:
      'hsl(25.110132158590307, 89.0196078431%, 95%)',
    backgroundColorForCollapsiblePanelHeaderIconWhenDisabled:
      'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForSelectInputOptionWhenHovered: 'hsl(0, 0%, 90%)',
    backgroundColorForAvatar: 'hsl(0, 0%, 60%)',
    backgroundColorForAvatarWhenHighlighted: '#ccc',
    backgroundColorForStampAsPositive: 'hsl(172.9608938547486, 100%, 85%)',
    backgroundColorForLocalizedMultilineTextInputLabel:
      'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForLocalizedMultilineTextInputLabelWhenDisabled:
      'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForTooltip: '#213c45',
    backgroundColorForViewSwitcher: '#fff',
    backgroundColorForViewSwitcherWhenDisabled: 'hsl(195, 35.2941176471%, 98%)',
    backgroundColorForViewSwitcherWhenSelected: 'hsl(0, 0%, 95%)',
    backgroundColorForViewSwitcherWhenHovered: 'hsl(0, 0%, 90%)',
    backgroundColorForContentNotificationWhenError: '#fff',
    backgroundColorForContentNotificationWhenInfo: '#fff',
    backgroundColorForContentNotificationWhenWarning: '#fff',
    backgroundColorForContentNotificationWhenSuccess: '#fff',
    backgroundColorForContentNotificationIconWhenError: '#e60050',
    backgroundColorForContentNotificationIconWhenInfo: '#078cdf',
    backgroundColorForContentNotificationIconWhenWarning: '#f16d0e',
    backgroundColorForContentNotificationIconWhenSuccess: '#00b39e',
    borderForButtonAsSecondary: 'none',
    borderForButtonAsSecondaryWhenHovered: 'none',
    borderForButtonAsSecondaryWhenActive: 'none',
    borderForCardWhenRaised: 'none',
    borderForCollapsiblePanelHeaderIconWhenDisabled:
      '1px solid var(--color-neutral)',
    borderForViewSwitcher: 'none',
    borderColorForInput: 'hsl(0, 0%, 60%)',
    borderColorForInputWhenFocused: '#00b39e',
    borderColorForInputWhenDisabled: '#ccc',
    borderColorForInputWhenReadonly: '#ccc',
    borderColorForInputWhenError: '#e60050',
    borderColorForInputWhenWarning: '#f16d0e',
    borderColorForInputWhenHovered: '#00b39e',
    borderColorForTag: 'hsl(0, 0%, 60%)',
    borderColorForTagWarning: '#f16d0e',
    borderColorForTagWhenFocused: '#00b39e',
    borderColorForTagWhenHovered: '#f16d0e',
    borderColorForButtonAsIcon: '#fff',
    borderColorForButtonAsIconAsInfo: '#078cdf',
    borderColorForButtonAsIconAsPrimary: '#00b39e',
    borderColorForButtonAsIconWhenDisabled: '#ccc',
    borderColorForTableHeader: '#ccc',
    borderColorForTableHeaderAsBottom: '#213c45',
    borderColorForTableManagerDroppableList: 'hsl(0, 0%, 60%)',
    borderColorForCollapsiblePanelHeader: 'hsl(0, 0%, 60%)',
    borderColorForStampWhenError: '#e60050',
    borderColorForStampWhenWarning: '#f16d0e',
    borderColorForStampAsPositive: 'hsl(172.9608938547486, 100%, 40%)',
    borderColorForStampAsInformation: '#078cdf',
    borderColorForStampAsPrimary: 'hsl(172.9608938547486, 100%, 25%)',
    borderColorForStampAsSecondary: 'hsl(0, 0%, 60%)',
    borderColorForLocalizedMultilineTextInputLabel: '#ccc',
    borderColorForLocalizedMultilineTextInputLabelWhenReadonly: '#ccc',
    borderColorForContentNotificationWhenError: '#e60050',
    borderColorForContentNotificationWhenInfo: '#078cdf',
    borderColorForContentNotificationWhenWarning: '#f16d0e',
    borderColorForContentNotificationWhenSuccess: '#00b39e',
    borderColorForGroupHeadingSelectInputOptions: '#ccc',
    borderColorForSelectInputMenu: '#00b39e',
    borderColorForSelectInputWhenReadonly: '#ccc',
    borderColorForSelectInputMenuWhenWarning: '#f16d0e',
    borderColorForSelectInputMenuWhenError: '#e60050',
    borderRadiusForButtonAsBig: '6px',
    borderRadiusForButtonAsSmall: '4px',
    borderRadiusForButtonAsIconAsBig: '6px',
    borderRadiusForButtonAsIconAsMedium: '4px',
    borderRadiusForButtonAsIconAsSmall: '2px',
    borderRadiusForInput: '6px',
    borderRadiusForTag: '2px',
    borderRadiusForCard: '6px',
    borderRadiusForTableManagerDroppableList: '6px',
    borderRadiusForStamp: '2px',
    borderRadiusForViewSwitcher: '6px',
    borderRadiusForContentNotification:
      '0 var(--border-radius-6) var(--border-radius-6) 0',
    borderRadiusForContentNotificationIcon:
      'var(--border-radius-6) 0 0 var(--border-radius-6)',
    borderWidthForInput: '1px',
    borderWidthForInputWhenWarning: '1px',
    borderWidthForInputWhenError: '1px',
    borderWidthForInputWhenFocused: '1px',
    borderWidthForTag: '1px',
    borderWidthForSelectInput: '1px',
    borderWidthForContentNotificationIcon: '0px',
    borderLeftWidthForContentNotification: '1px',
    boxShadowForDatetimeInputWhenHovered: 'inset 0 0 0 2px',
    boxShadowForViewSwitcher:
      '0 1px 1px 0 rgba(0, 0, 0, 0.24), 0 -1px 1px 0 rgba(0, 0, 0, 0.12)',
    boxShadowForViewSwitcherWhenSelected:
      'inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25)',
    boxShadowForSelectInputWhenFocused: 'inset 0 0 0 2px',
    fontColorForText: '#1a1a1a',
    fontColorForInput: '#1a1a1a',
    fontColorForInputWhenDisabled: 'hsl(0, 0%, 60%)',
    fontColorForInputWhenError: '#e60050',
    fontColorForInputWhenReadonly: 'hsl(0, 0%, 60%)',
    fontColorForInputWhenWarning: '#f16d0e',
    fontColorForTag: '#1a1a1a',
    fontColorForTagRemoveIcon: '#1a1a1a',
    fontColorForTagDragIcon: '#1a1a1a',
    fontColorForTagRemoveIconWhenHovered: '#f16d0e',
    fontColorForTagWhenDisabled: 'hsl(0, 0%, 60%)',
    fontColorForTextWhenInverted: '#fff',
    fontColorForTableHeader: '#fff',
    fontColorForLocalizedMultilineTextInputLabel: 'hsl(0, 0%, 60%)',
    fontColorForViewSwitcher: '#1a1a1a',
    fontColorForViewSwitcherWhenDisabled: 'hsl(0, 0%, 60%)',
    fontColorForViewSwitcherWhenSelected: '#1a1a1a',
    fontColorForClearInputIcon: '#1a1a1a',
    fontColorForClearInputIconWhenHovered: '#f16d0e',
    fontColorForContentNotification: '#1a1a1a',
    fontColorForContentNotificationIconWhenError: '#fff',
    fontColorForContentNotificationIconWhenWarning: '#fff',
    fontColorForContentNotificationIconWhenSuccess: '#fff',
    fontColorForContentNotificationIconWhenInfo: '#fff',
    fontColorForSearchInputIcon: '#1a1a1a',
    fontColorForSearchInputIconWhenHovered: '#1a1a1a',
    fontColorForSelectInputIcon: '#1a1a1a',
    fontColorForSelectInputWhenError: 'hsl(0, 0%, 60%)',
    fontColorForSelectInputWhenWarning: 'hsl(0, 0%, 60%)',
    fontColorForSelectInputIconWhenError: '#1a1a1a',
    fontColorForSelectInputIconWhenWarning: '#1a1a1a',
    heightForButtonAsBig: '32px',
    heightForButtonAsSmall: '24px',
    heightForButtonAsIconAsBig: '32px',
    heightForButtonAsIconAsMedium: '24px',
    heightForButtonAsIconAsSmall: '16px',
    heightForInput: '32px',
    heightForViewSwitcher: '32px',
    heightForViewSwitcherWhenCondensed: '24px',
    widthForAvatarAsMedium: '48px',
    placeholderFontColorForInput: 'hsl(0, 0%, 60%)',
    fontSizeForButton: '1rem',
    fontSizeForInput: '1rem',
    fontSizeForTextAsH1: '2.4615rem',
    fontSizeForTextAsH2: '1.8462rem',
    fontSizeForTextAsH3: '1.5385rem',
    fontSizeForTextAsH4: '1.2308rem',
    fontSizeForTextAsH5: '1.0769rem',
    fontSizeForTextAsBody: '1rem',
    fontSizeForTextAsDetail: '0.9231rem',
    fontSizeForBody: '13px',
    fontSizeForLink: '1rem',
    fontSizeForStamp: '1rem',
    fontSizeForViewSwitcher: '1rem',
    fontSizeForTable: '1rem',
    fontSizeForAvatarAsSmall: '1rem',
    fontSizeForAvatarAsMedium: '1.5rem',
    fontSizeForAvatarAsBig: '3rem',
    fontSizeForLocalizedMultilineTextInputLabel: '0.9231rem',
    fontSizeForContentNotification: '1rem',
    iconColorForDatetimeInputIcon: '#1a1a1a',
    iconColorForDatetimeInputIconWhenHovered: '#f16d0e',
    lineHeightForTextAsH1: 'inherit',
    lineHeightForTextAsH2: 'inherit',
    lineHeightForTextAsH3: 'inherit',
    lineHeightForTextAsH4: 'inherit',
    lineHeightForTextAsH5: 'inherit',
    lineHeightForTextAsBody: 'inherit',
    lineHeightForTextAsDetail: 'inherit',
    fontWeightForTextAsH1: '300',
    fontWeightForTextAsH2: '300',
    fontWeightForTextAsH3: '300',
    fontWeightForTextAsH4: '400',
    fontWeightForTextAsH5: '400',
    fontWeightForTextAsBody: '400',
    fontWeightForTextAsDetail: '400',
    fontWeightForButton: '400',
    fontWeightForTableHeader: '400',
    marginForTableHeader: '8px',
    marginForTableAsCondensed: '8px',
    marginForViewSwitcherIcon: '0 var(--spacing-10) 0 0',
    marginForGroupHeadingSelectInputOptions: '4px',
    marginForSelectInputIcon: '4px',
    marginLeftForSelectInputIcon: 'inherit',
    paddingForStamp: 'var(--spacing-10) var(--spacing-20)',
    paddingForStampAsCondensed: '1px var(--spacing-10)',
    paddingForTag: '5px var(--spacing-20)',
    paddingForTableHeader: '16px',
    paddingForTableHeaderAsCondensed: '8px',
    paddingForTableCell: '16px',
    paddingForTableCellAsCondensed: '8px',
    paddingForTableManagerDroppableList: '8px',
    paddingForTableManagerSettingsPanel: '16px',
    paddingForTableManagerDraggableTag: '4px',
    paddingForCollapsiblePanelHeader: 'var(--spacing-20) var(--spacing-30)',
    paddingForCollapsiblePanelHeaderAsCondensed: '8px',
    paddingForCollapsiblePanelSectionWrapper: '16px',
    paddingForCollapsiblePanelSectionWrapperAsCondensed: '8px',
    paddingForCollapsiblePanelSectionDescription: '0 0 var(--spacing-50)',
    paddingForCollapsiblePanelSectionDescriptionAsCondensed:
      '0 0 var(--spacing-30)',
    paddingForInput: '8px',
    paddingForMultilineInput: 'var(--spacing-10) var(--spacing-20)',
    paddingForLocalizedRichTextInputLabel: '0 var(--spacing-20)',
    paddingForLocalizedMultilineTextInputLabel: '0 var(--spacing-20)',
    paddingForTagRemoveIcon: '0 var(--spacing-10)',
    paddingForTooltip: 'var(--spacing-10) var(--spacing-20)',
    paddingForViewSwitcher: '0 var(--spacing-30) 0 var(--spacing-30)',
    paddingForViewSwitcherWhenCondensed:
      '0 var(--spacing-20) 0 var(--spacing-20)',
    paddingForContentNotification: 'var(--spacing-20)',
    paddingForContentNotificationIcon: 'var(--spacing-20) var(--spacing-30)',
    paddingLeftForSelectInputOptions: '8px',
    paddingRightForSelectInputOptions: '8px',
    paddingTopForSelectInputOptions: '4px',
    paddingBottomForSelectInputOptions: '4px',
    paddingForGroupHeadingSelectInputOptions: '8px',
    paddingForSelectInputMenu: 'inherit',
    shadowForButton:
      '0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24)',
    shadowForButtonWhenFocused:
      '0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24)',
    shadowForButtonWhenHovered:
      '0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24)',
    shadowForButtonWhenActive:
      'inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25)',
    shadowForButtonWhenDisabled: '0 0 0 1px var(--color-neutral) inset',
    shadowBoxTagWhenHovered:
      '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    shadowForCardWhenRaised:
      '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    shadowForInput: 'none',
    shadowForInputWhenFocused: 'inset 0 0 0 2px var(--color-primary)',
    shadowForInputWhenError: 'none',
    shadowForInputWhenWarning: 'none',
    shadowForTooltip:
      '0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12)',
    shadowForSelectInputMenu:
      '0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24)',
    fontSizeM: '1rem',
    bigButtonHeight: '32px',
    smallButtonHeight: '24px',
    sizeHeightInput: '32px',
    fontFamilyDefault: "'Open Sans', sans-serif",
    fontSizeDefault: '1rem',
    fontSizeSmall: '0.9231rem',
    shadowBoxTagHover:
      '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    sizeHeightTag: '26px',
    standardInputHeight: '32px',
  },
  test: {
    colorPrimary: '#00b39e',
    fontFamily: "'Inter', system-ui",
    backgroundColorForButtonWhenActive: 'hsl(0deg 0% 10% / 10%)',
    backgroundColorForButtonWhenHovered: 'hsl(0deg 0% 10% / 5%)',
    backgroundColorForButtonAsPrimaryWhenActive: '#15A390',
    backgroundColorForButtonAsPrimaryWhenHovered: '#17AB97',
    backgroundColorForButtonAsIconAsPrimaryWhenActive: '#15A390',
    backgroundColorForButtonAsIconAsPrimaryWhenHovered: '#00b39e',
    backgroundColorForButtonAsIconAsInfoWhenActive: '#057FCC',
    backgroundColorForButtonAsIconAsInfoWhenHovered: '#078cdf',
    backgroundColorForButtonAsUrgentWhenActive: '#DC630A',
    backgroundColorForButtonAsUrgentWhenHovered: '#E7680D',
    backgroundColorForButtonWhenDisabled: 'hsl(0, 0%, 95%)',
    backgroundColorForTableCellWhenHovered: 'hsl(0, 0%, 95%)',
    backgroundColorForTableHeader: '#fff',
    backgroundColorForCollapsiblePanelHeaderIconWhenDisabled: '#fff',
    backgroundColorForInputWhenHovered: 'hsl(0, 0%, 98%)',
    backgroundColorForInputWhenDisabled: 'hsl(0, 0%, 95%)',
    backgroundColorForInputWhenActive:
      'hsl(203.05555555555554, 93.9130434783%, 95%)',
    backgroundColorForInputWhenReadonly: 'hsl(0, 0%, 95%)',
    backgroundColorForAvatar: '#213c45',
    backgroundColorForAvatarWhenHighlighted: 'hsl(195, 35.2941176471%, 30%)',
    backgroundColorForStampAsPositive: 'hsl(172.9608938547486, 100%, 95%)',
    backgroundColorForLocalizedMultilineTextInputLabel: '#fff',
    backgroundColorForLocalizedMultilineTextInputLabelWhenDisabled:
      'hsl(0, 0%, 95%)',
    backgroundColorForTooltip: 'hsl(195, 35.2941176471%, 10%)',
    backgroundColorForViewSwitcherWhenDisabled: '#fff',
    backgroundColorForViewSwitcherWhenSelected: 'hsl(0, 0%, 95%)',
    backgroundColorForViewSwitcherWhenHovered: 'hsl(0, 0%, 95%)',
    backgroundColorForContentNotificationWhenError:
      'hsl(339.1304347826087, 100%, 95%)',
    backgroundColorForContentNotificationWhenInfo:
      'hsl(203.05555555555554, 93.9130434783%, 95%)',
    backgroundColorForContentNotificationWhenWarning:
      'hsl(25.110132158590307, 89.0196078431%, 95%)',
    backgroundColorForContentNotificationWhenSuccess:
      'hsl(172.9608938547486, 100%, 95%)',
    backgroundColorForContentNotificationIconWhenError:
      'hsl(339.1304347826087, 100%, 95%)',
    backgroundColorForContentNotificationIconWhenInfo:
      'hsl(203.05555555555554, 93.9130434783%, 95%)',
    backgroundColorForContentNotificationIconWhenWarning:
      'hsl(25.110132158590307, 89.0196078431%, 95%)',
    backgroundColorForContentNotificationIconWhenSuccess:
      'hsl(172.9608938547486, 100%, 95%)',
    backgroundColorForSelectInputOptionWhenHovered: 'hsl(0, 0%, 98%)',
    borderForButtonAsSecondary: '1px solid var(--color-neutral)',
    borderForButtonAsSecondaryWhenHovered: '1px solid var(--color-neutral)',
    borderForButtonAsSecondaryWhenActive: '1px solid var(--color-neutral)',
    borderForCardWhenRaised: '1px solid var(--color-neutral-90)',
    borderForCollapsiblePanelHeaderIconWhenDisabled: 'none',
    borderForViewSwitcher: '1px solid var(--color-neutral)',
    borderColorForInput: '#ccc',
    borderColorForInputWhenDisabled: '#ccc',
    borderColorForInputWhenHovered: '#ccc',
    borderColorForInputWhenReadonly: 'hsl(0, 0%, 90%)',
    borderColorForInputWhenFocused: '#00b39e',
    borderColorForButtonAsIcon: '#ccc',
    borderColorForButtonAsIconAsInfo: '#ccc',
    borderColorForButtonAsIconAsPrimary: '#ccc',
    borderColorForButtonAsIconWhenDisabled: '#fff',
    borderColorForCardWhenRaised: 'hsl(0, 0%, 90%)',
    borderColorForTableHeader: '#fff',
    borderColorForTableHeaderAsBottom: 'hsl(0, 0%, 90%)',
    borderColorForTableManagerDroppableList: '#ccc',
    borderColorForCollapsiblePanelHeader: 'hsl(0, 0%, 90%)',
    borderColorForStampWhenError: 'hsl(339.1304347826087, 100%, 85%)',
    borderColorForStampWhenWarning:
      'hsl(25.110132158590307, 89.0196078431%, 85%)',
    borderColorForStampAsPositive: 'hsl(172.9608938547486, 100%, 85%)',
    borderColorForStampAsInformation:
      'hsl(203.05555555555554, 93.9130434783%, 85%)',
    borderColorForStampAsPrimary: 'hsl(172.9608938547486, 100%, 85%)',
    borderColorForStampAsSecondary: 'hsl(0, 0%, 85%)',
    borderColorForLocalizedMultilineTextInputLabelWhenReadonly:
      'hsl(0, 0%, 90%)',
    borderColorForTag: '#ccc',
    borderColorForTagWhenHovered: '#ccc',
    borderColorForContentNotificationWhenError:
      'hsl(339.1304347826087, 100%, 85%)',
    borderColorForContentNotificationWhenInfo:
      'hsl(203.05555555555554, 93.9130434783%, 85%)',
    borderColorForContentNotificationWhenWarning:
      'hsl(25.110132158590307, 89.0196078431%, 85%)',
    borderColorForContentNotificationWhenSuccess:
      'hsl(172.9608938547486, 100%, 85%)',
    borderColorForGroupHeadingSelectInputOptions: 'hsl(0, 0%, 90%)',
    borderColorForSelectInputMenu: '#fff',
    borderColorForSelectInputWhenReadonly: 'hsl(0, 0%, 95%)',
    borderColorForSelectInputMenuWhenWarning: '#fff',
    borderColorForSelectInputMenuWhenError: '#fff',
    borderRadiusForButtonAsBig: '4px',
    borderRadiusForButtonAsSmall: '4px',
    borderRadiusForButtonAsIconAsBig: '4px',
    borderRadiusForButtonAsIconAsMedium: '4px',
    borderRadiusForButtonAsIconAsSmall: '2px',
    borderRadiusForCard: '4px',
    borderRadiusForTableManagerDroppableList: '4px',
    borderRadiusForInput: '4px',
    borderRadiusForStamp: '20px',
    borderRadiusForViewSwitcher: '4px',
    borderRadiusForContentNotification:
      '0 var(--border-radius-4) var(--border-radius-4) 0',
    borderRadiusForContentNotificationIcon:
      'var(--border-radius-4) 0 0 var(--border-radius-4)',
    borderWidthForTag: '1px 1px 1px 0',
    borderWidthForContentNotificationIcon: '1px',
    borderLeftWidthForContentNotification: '0px',
    borderWidthForSelectInput: '2px',
    boxShadowForDatetimeInputWhenHovered: 'inset 0 0 0 1px',
    boxShadowForViewSwitcher: 'none',
    boxShadowForViewSwitcherWhenSelected: 'none',
    boxShadowForSelectInputWhenFocused: 'inset 0 0 0 1px',
    fontColorForTableHeader: 'hsl(0, 0%, 40%)',
    fontColorForInputWhenReadonly: 'hsl(0, 0%, 40%)',
    fontColorForTagRemoveIcon: 'hsl(0, 0%, 40%)',
    fontColorForTagDragIcon: 'hsl(0, 0%, 40%)',
    fontColorForTagRemoveIconWhenHovered: '#e60050',
    fontColorForViewSwitcher: 'hsl(0, 0%, 40%)',
    fontColorForContentNotificationIconWhenError: '#e60050',
    fontColorForContentNotificationIconWhenWarning: '#f16d0e',
    fontColorForContentNotificationIconWhenSuccess: '#00b39e',
    fontColorForContentNotificationIconWhenInfo: '#078cdf',
    fontColorForClearInputIconWhenHovered: '#e60050',
    fontColorForClearInputIcon: 'hsl(0, 0%, 40%)',
    fontColorForSearchInputIcon: 'hsl(0, 0%, 60%)',
    fontColorForSearchInputIconWhenHovered: '#00b39e',
    fontColorForSelectInputIcon: 'hsl(0, 0%, 60%)',
    fontColorForSelectInputWhenError: '#e60050',
    fontColorForSelectInputWhenWarning: '#f16d0e',
    fontColorForSelectInputIconWhenError: '#e60050',
    fontColorForSelectInputIconWhenWarning: '#f16d0e',
    fontSizeForInput: '1rem',
    fontSizeForTextAsH1: '1.5rem',
    fontSizeForTextAsH2: '1.25rem',
    fontSizeForTextAsH3: '1.125rem',
    fontSizeForTextAsH4: '1rem',
    fontSizeForTextAsH5: '1rem',
    fontSizeForTextAsBody: '1rem',
    fontSizeForTextAsDetail: '0.875rem',
    fontSizeForBody: '16px',
    fontSizeForButton: '0.875rem',
    fontSizeForLink: 'inherit',
    fontSizeForStamp: '0.875rem',
    fontSizeForViewSwitcher: '0.875rem',
    fontSizeForTable: '0.875rem',
    fontSizeForAvatarAsSmall: '0.875rem',
    fontSizeForAvatarAsMedium: '1rem',
    fontSizeForAvatarAsBig: '2.5rem',
    fontSizeForLocalizedMultilineTextInputLabel: '1rem',
    lineHeightForTextAsH1: '2.125rem',
    lineHeightForTextAsH2: '1.75rem',
    lineHeightForTextAsH3: '1.5rem',
    lineHeightForTextAsH4: '1.375rem',
    lineHeightForTextAsH5: '1.375rem',
    lineHeightForTextAsBody: '1.625rem',
    lineHeightForTextAsDetail: '1.375rem',
    fontWeightForTextAsH1: '600',
    fontWeightForTextAsH2: '500',
    fontWeightForTextAsH3: '500',
    fontWeightForTextAsH4: '500',
    fontWeightForTextAsH5: '500',
    fontWeightForTextAsBody: '400',
    fontWeightForTextAsDetail: '400',
    fontWeightForButton: '500',
    fontWeightForTableHeader: '600',
    heightForButtonAsBig: '40px',
    heightForButtonAsSmall: '32px',
    heightForButtonAsIconAsBig: '40px',
    heightForButtonAsIconAsMedium: '32px',
    heightForButtonAsIconAsSmall: '16px',
    heightForInput: '40px',
    heightForViewSwitcher: '40px',
    heightForViewSwitcherWhenCondensed: '32px',
    iconColorForDatetimeInputIcon: 'hsl(0, 0%, 40%)',
    iconColorForDatetimeInputIconWhenHovered: '#e60050',
    widthForAvatarAsMedium: '40px',
    marginForTableHeader: '16px',
    marginForTableCellAsCondensed: '8px',
    marginForViewSwitcherIcon: '0 var(--spacing-20) 0 0',
    marginForGroupHeadingSelectInputOptions: '8px',
    marginForSelectInputIcon: '8px',
    marginLeftForSelectInputIcon: '8px',
    paddingForStamp: '4px 12px',
    paddingForStampAsCondensed: '0 var(--spacing-20)',
    paddingForTag: '2px 12px',
    paddingForTableHeader: '24px',
    paddingForTableHeaderAsCondensed: '24px',
    paddingForTableCell: 'var(--spacing-30) var(--spacing-40)',
    paddingForTableCellAsCondensed: 'var(--spacing-20) var(--spacing-40)',
    paddingForTableManagerDroppableList: '16px',
    paddingForTableManagerSettingsPanel: 'var(--spacing-40) var(--spacing-50)',
    paddingForTableManagerDraggableTag: 'var(--spacing-10) 0',
    paddingForCollapsiblePanelHeader: 'var(--spacing-30) 0',
    paddingForCollapsiblePanelHeaderAsCondensed: 'var(--spacing-20) 0',
    paddingForCollapsiblePanelSectionWrapper:
      'var(--spacing-50) 0 var(--spacing-70) calc(var(--spacing-30) + var(--spacing-10))',
    paddingForCollapsiblePanelSectionWrapperAsCondensed:
      'var(--spacing-40) 0 var(--spacing-70) calc(var(--spacing-30) + var(--spacing-10))',
    paddingForCollapsiblePanelSectionDescription: '0 0 var(--spacing-40)',
    paddingForCollapsiblePanelSectionDescriptionAsCondensed:
      '0 0 var(--spacing-40)',
    paddingForInput: '16px',
    paddingForMultilineInput: '8px',
    paddingForLocalizedRichTextInputLabel: '8px',
    paddingForLocalizedMultilineTextInputLabel: '0 12px',
    paddingForTagRemoveIcon: '0 12px',
    paddingForTooltip: 'var(--spacing-20) 12px',
    paddingForViewSwitcher: '0 var(--spacing-30) 0 var(--spacing-30)',
    paddingForViewSwitcherWhenCondensed: '0 12px 0 12px',
    paddingForContentNotification:
      'var(--spacing-20) var(--spacing-30) var(--spacing-20) var(--spacing-20)',
    paddingForContentNotificationIcon:
      'var(--spacing-20) 0 var(--spacing-20) var(--spacing-30)',
    paddingLeftForSelectInputOptions: '16px',
    paddingRightForSelectInputOptions: '16px',
    paddingTopForSelectInputOptions: '8px',
    paddingBottomForSelectInputOptions: '8px',
    paddingForGroupHeadingSelectInputOptions: '16px',
    paddingForSelectInputMenu: 'var(--spacing-10) 0',
    shadowForButton: 'none',
    shadowForButtonWhenFocused: 'none',
    shadowForButtonWhenHovered: 'none',
    shadowForButtonWhenActive: 'none',
    shadowForButtonWhenDisabled: 'none',
    shadowForCardWhenRaised: '0 1px 5px 0 rgba(0, 0, 0, 0.05)',
    shadowForInput: 'none',
    shadowForInputWhenFocused: 'inset 0 0 0 1px var(--color-primary)',
    shadowForInputWhenError: 'inset 0 0 0 1px var(--color-error)',
    shadowForInputWhenWarning: 'inset 0 0 0 1px var(--color-warning)',
    shadowForTooltip: '0px 1px 2px 0px rgba(0, 0, 0, 0.25)',
    shadowForSelectInputMenu: '0 2px 5px 0px rgba(0, 0, 0, 0.15)',
  },
} as const;

const designTokens = {
  colorPrimary: 'var(--color-primary, #00b39e)',
  colorPrimary25: 'var(--color-primary-25, hsl(172.9608938547486, 100%, 25%))',
  colorPrimary40: 'var(--color-primary-40, hsl(172.9608938547486, 100%, 40%))',
  colorPrimary85: 'var(--color-primary-85, hsl(172.9608938547486, 100%, 85%))',
  colorPrimary95: 'var(--color-primary-95, hsl(172.9608938547486, 100%, 95%))',
  colorAccent: 'var(--color-accent, #213c45)',
  colorAccent10: 'var(--color-accent-10, hsl(195, 35.2941176471%, 10%))',
  colorAccent20: 'var(--color-accent-20, hsl(195, 35.2941176471%, 20%))',
  colorAccent30: 'var(--color-accent-30, hsl(195, 35.2941176471%, 30%))',
  colorAccent40: 'var(--color-accent-40, hsl(195, 35.2941176471%, 40%))',
  colorAccent90: 'var(--color-accent-90, hsl(195, 35.2941176471%, 90%))',
  colorAccent95: 'var(--color-accent-95, hsl(195, 35.2941176471%, 95%))',
  colorAccent98: 'var(--color-accent-98, hsl(195, 35.2941176471%, 98%))',
  colorNeutral: 'var(--color-neutral, #ccc)',
  colorNeutral05: 'var(--color-neutral-05, hsl(0deg 0% 80% / 5%))',
  colorNeutral10: 'var(--color-neutral-10, hsl(0deg 0% 80% / 10%))',
  colorNeutral40: 'var(--color-neutral-40, hsl(0, 0%, 40%))',
  colorNeutral60: 'var(--color-neutral-60, hsl(0, 0%, 60%))',
  colorNeutral85: 'var(--color-neutral-85, hsl(0, 0%, 85%))',
  colorNeutral90: 'var(--color-neutral-90, hsl(0, 0%, 90%))',
  colorNeutral95: 'var(--color-neutral-95, hsl(0, 0%, 95%))',
  colorNeutral98: 'var(--color-neutral-98, hsl(0, 0%, 98%))',
  colorInfo: 'var(--color-info, #078cdf)',
  colorInfo40:
    'var(--color-info-40, hsl(203.05555555555554, 93.9130434783%, 40%))',
  colorInfo85:
    'var(--color-info-85, hsl(203.05555555555554, 93.9130434783%, 85%))',
  colorInfo95:
    'var(--color-info-95, hsl(203.05555555555554, 93.9130434783%, 95%))',
  colorWarning: 'var(--color-warning, #f16d0e)',
  colorWarning25:
    'var(--color-warning-25, hsl(25.110132158590307, 89.0196078431%, 25%))',
  colorWarning40:
    'var(--color-warning-40, hsl(25.110132158590307, 89.0196078431%, 40%))',
  colorWarning85:
    'var(--color-warning-85, hsl(25.110132158590307, 89.0196078431%, 85%))',
  colorWarning95:
    'var(--color-warning-95, hsl(25.110132158590307, 89.0196078431%, 95%))',
  colorError: 'var(--color-error, #e60050)',
  colorError25: 'var(--color-error-25, hsl(339.1304347826087, 100%, 25%))',
  colorError40: 'var(--color-error-40, hsl(339.1304347826087, 100%, 40%))',
  colorError85: 'var(--color-error-85, hsl(339.1304347826087, 100%, 85%))',
  colorError95: 'var(--color-error-95, hsl(339.1304347826087, 100%, 95%))',
  colorSolid: 'var(--color-solid, #1a1a1a)',
  colorSolid05: 'var(--color-solid-05, hsl(0deg 0% 10% / 5%))',
  colorSolid10: 'var(--color-solid-10, hsl(0deg 0% 10% / 10%))',
  colorSurface: 'var(--color-surface, #fff)',
  borderRadius1: 'var(--border-radius-1, 1px)',
  borderRadius2: 'var(--border-radius-2, 2px)',
  borderRadius4: 'var(--border-radius-4, 4px)',
  borderRadius6: 'var(--border-radius-6, 6px)',
  borderRadius20: 'var(--border-radius-20, 20px)',
  borderWidth1: 'var(--border-width-1, 1px)',
  borderWidth2: 'var(--border-width-2, 2px)',
  fontFamily: "var(--font-family, 'Open Sans', sans-serif)",
  fontSize10: 'var(--font-size-10, 0.75rem)',
  fontSize20: 'var(--font-size-20, 0.875rem)',
  fontSize30: 'var(--font-size-30, 1rem)',
  fontSize40: 'var(--font-size-40, 1.125rem)',
  fontSize50: 'var(--font-size-50, 1.25rem)',
  fontSize60: 'var(--font-size-60, 1.5rem)',
  fontSize70: 'var(--font-size-70, 2rem)',
  fontSize80: 'var(--font-size-80, 2.5rem)',
  fontSize15: 'var(--font-size-15, 0.9231rem)',
  fontSize35: 'var(--font-size-35, 1.0769rem)',
  fontSize45: 'var(--font-size-45, 1.2308rem)',
  fontSize63: 'var(--font-size-63, 1.5385rem)',
  fontSize66: 'var(--font-size-66, 1.8462rem)',
  fontSize69: 'var(--font-size-69, 2.4615rem)',
  fontSize78: 'var(--font-size-78, 3rem)',
  fontWeight300: 'var(--font-weight-300, 300)',
  fontWeight400: 'var(--font-weight-400, 400)',
  fontWeight500: 'var(--font-weight-500, 500)',
  fontWeight600: 'var(--font-weight-600, 600)',
  fontWeight700: 'var(--font-weight-700, 700)',
  lineHeight10: 'var(--line-height-10, 1.25rem)',
  lineHeight20: 'var(--line-height-20, 1.375rem)',
  lineHeight30: 'var(--line-height-30, 1.5rem)',
  lineHeight40: 'var(--line-height-40, 1.625rem)',
  lineHeight50: 'var(--line-height-50, 1.75rem)',
  lineHeight60: 'var(--line-height-60, 2.125rem)',
  shadow0: 'var(--shadow-0, none)',
  shadow1:
    'var(--shadow-1, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  shadow2:
    'var(--shadow-2, 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23))',
  shadow3:
    'var(--shadow-3, 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23))',
  shadow4:
    'var(--shadow-4, 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22))',
  shadow5:
    'var(--shadow-5, 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22))',
  shadow6: 'var(--shadow-6, 0 -1px 2px 0 rgba(0, 0, 0, 0.2))',
  shadow7:
    'var(--shadow-7, 0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24))',
  shadow8:
    'var(--shadow-8, 0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24))',
  shadow9:
    'var(--shadow-9, inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25))',
  shadow10: 'var(--shadow-10, 0 0 0 1px rgba(224, 230, 237, 0.5))',
  shadow11:
    'var(--shadow-11, 0 1px 0.5px rgba(0, 0, 0, 0.24), 0 -1px 0.75px rgba(0, 0, 0, 0.12))',
  shadow12: 'var(--shadow-12, 0 0 1px rgba(0, 0, 0, 0.25))',
  shadow13: 'var(--shadow-13, 0 0 1px rgba(0, 0, 0, 0.25))',
  shadow14: 'var(--shadow-14, 0 0 0.5px rgba(0, 0, 0, 0.1))',
  shadow15:
    'var(--shadow-15, 0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12))',
  shadow16:
    'var(--shadow-16, 0.5px 1.5px 4px 1px rgba(0, 0, 0, 0.25), -0.5px -0.5px 4px 1px rgba(0, 0, 0, 0.25))',
  constraintScale: 'var(--constraint-scale, 100%)',
  constraint1: 'var(--constraint-1, 42px)',
  constraint2: 'var(--constraint-2, 84px)',
  constraint3: 'var(--constraint-3, 142px)',
  constraint4: 'var(--constraint-4, 184px)',
  constraint5: 'var(--constraint-5, 242px)',
  constraint6: 'var(--constraint-6, 284px)',
  constraint7: 'var(--constraint-7, 342px)',
  constraint8: 'var(--constraint-8, 384px)',
  constraint9: 'var(--constraint-9, 442px)',
  constraint10: 'var(--constraint-10, 484px)',
  constraint11: 'var(--constraint-11, 542px)',
  constraint12: 'var(--constraint-12, 584px)',
  constraint13: 'var(--constraint-13, 642px)',
  constraint14: 'var(--constraint-14, 684px)',
  constraint15: 'var(--constraint-15, 742px)',
  constraint16: 'var(--constraint-16, 784px)',
  spacingXs: 'var(--spacing-xs, 4px)',
  spacingS: 'var(--spacing-s, 8px)',
  spacingM: 'var(--spacing-m, 16px)',
  spacingL: 'var(--spacing-l, 24px)',
  spacingXl: 'var(--spacing-xl, 32px)',
  spacing10: 'var(--spacing-10, 4px)',
  spacing20: 'var(--spacing-20, 8px)',
  spacing30: 'var(--spacing-30, 16px)',
  spacing40: 'var(--spacing-40, 24px)',
  spacing50: 'var(--spacing-50, 32px)',
  spacing60: 'var(--spacing-60, 48px)',
  spacing70: 'var(--spacing-70, 64px)',
  transitionLinear80Ms: 'var(--transition-linear-80-ms, 80ms linear)',
  transitionEaseinout150Ms:
    'var(--transition-easeinout-150-ms, 150ms ease-in-out)',
  transitionStandard: 'var(--transition-standard, 200ms ease)',
  breakPointMobile: 'var(--break-point-mobile, 768px)',
  breakPointDesktop: 'var(--break-point-desktop, 1024px)',
  breakPointBiggerdesktop: 'var(--break-point-biggerdesktop, 1280px)',
  breakPointGiantdesktop: 'var(--break-point-giantdesktop, 1680px)',
  breakPointJumbodesktop: 'var(--break-point-jumbodesktop, 1920px)',
  backgroundColorForButtonWhenActive:
    'var(--background-color-for-button-when-active, #fff)',
  backgroundColorForButtonWhenHovered:
    'var(--background-color-for-button-when-hovered, #fff)',
  backgroundColorForButtonAsPrimaryWhenActive:
    'var(--background-color-for-button-as-primary-when-active, #00b39e)',
  backgroundColorForButtonAsPrimaryWhenHovered:
    'var(--background-color-for-button-as-primary-when-hovered, hsl(172.9608938547486, 100%, 25%))',
  backgroundColorForButtonAsIconAsPrimaryWhenActive:
    'var(--background-color-for-button-as-icon-as-primary-when-active, #00b39e)',
  backgroundColorForButtonAsIconAsPrimaryWhenHovered:
    'var(--background-color-for-button-as-icon-as-primary-when-hovered, #00b39e)',
  backgroundColorForButtonAsIconAsInfoWhenActive:
    'var(--background-color-for-button-as-icon-as-info-when-active, #078cdf)',
  backgroundColorForButtonAsIconAsInfoWhenHovered:
    'var(--background-color-for-button-as-icon-as-info-when-hovered, #078cdf)',
  backgroundColorForButtonAsUrgentWhenActive:
    'var(--background-color-for-button-as-urgent-when-active, #f16d0e)',
  backgroundColorForButtonAsUrgentWhenHovered:
    'var(--background-color-for-button-as-urgent-when-hovered, hsl(25.110132158590307, 89.0196078431%, 25%))',
  backgroundColorForButtonWhenDisabled:
    'var(--background-color-for-button-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForInput: 'var(--background-color-for-input, #fff)',
  backgroundColorForInputWhenSelected:
    'var(--background-color-for-input-when-selected, hsl(195, 35.2941176471%, 95%))',
  backgroundColorForInputWhenDisabled:
    'var(--background-color-for-input-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForInputWhenHovered:
    'var(--background-color-for-input-when-hovered, #fff)',
  backgroundColorForInputWhenFocused:
    'var(--background-color-for-input-when-focused, #fff)',
  backgroundColorForInputWhenReadonly:
    'var(--background-color-for-input-when-readonly, #fff)',
  backgroundColorForInputWhenActive:
    'var(--background-color-for-input-when-active, hsl(195, 35.2941176471%, 95%))',
  backgroundColorForTableCellWhenHovered:
    'var(--background-color-for-table-cell-when-hovered, hsl(0, 0%, 90%))',
  backgroundColorForTableHeader:
    'var(--background-color-for-table-header, #213c45)',
  backgroundColorForTag: 'var(--background-color-for-tag, hsl(0, 0%, 95%))',
  backgroundColorForTagWarning:
    'var(--background-color-for-tag-warning, hsl(25.110132158590307, 89.0196078431%, 95%))',
  backgroundColorForCollapsiblePanelHeaderIconWhenDisabled:
    'var(--background-color-for-collapsible-panel-header-icon-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForSelectInputOptionWhenHovered:
    'var(--background-color-for-select-input-option-when-hovered, hsl(0, 0%, 90%))',
  backgroundColorForAvatar:
    'var(--background-color-for-avatar, hsl(0, 0%, 60%))',
  backgroundColorForAvatarWhenHighlighted:
    'var(--background-color-for-avatar-when-highlighted, #ccc)',
  backgroundColorForStampAsPositive:
    'var(--background-color-for-stamp-as-positive, hsl(172.9608938547486, 100%, 85%))',
  backgroundColorForLocalizedMultilineTextInputLabel:
    'var(--background-color-for-localized-multiline-text-input-label, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForLocalizedMultilineTextInputLabelWhenDisabled:
    'var(--background-color-for-localized-multiline-text-input-label-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForTooltip: 'var(--background-color-for-tooltip, #213c45)',
  backgroundColorForViewSwitcher:
    'var(--background-color-for-view-switcher, #fff)',
  backgroundColorForViewSwitcherWhenDisabled:
    'var(--background-color-for-view-switcher-when-disabled, hsl(195, 35.2941176471%, 98%))',
  backgroundColorForViewSwitcherWhenSelected:
    'var(--background-color-for-view-switcher-when-selected, hsl(0, 0%, 95%))',
  backgroundColorForViewSwitcherWhenHovered:
    'var(--background-color-for-view-switcher-when-hovered, hsl(0, 0%, 90%))',
  backgroundColorForContentNotificationWhenError:
    'var(--background-color-for-content-notification-when-error, #fff)',
  backgroundColorForContentNotificationWhenInfo:
    'var(--background-color-for-content-notification-when-info, #fff)',
  backgroundColorForContentNotificationWhenWarning:
    'var(--background-color-for-content-notification-when-warning, #fff)',
  backgroundColorForContentNotificationWhenSuccess:
    'var(--background-color-for-content-notification-when-success, #fff)',
  backgroundColorForContentNotificationIconWhenError:
    'var(--background-color-for-content-notification-icon-when-error, #e60050)',
  backgroundColorForContentNotificationIconWhenInfo:
    'var(--background-color-for-content-notification-icon-when-info, #078cdf)',
  backgroundColorForContentNotificationIconWhenWarning:
    'var(--background-color-for-content-notification-icon-when-warning, #f16d0e)',
  backgroundColorForContentNotificationIconWhenSuccess:
    'var(--background-color-for-content-notification-icon-when-success, #00b39e)',
  borderForButtonAsSecondary: 'var(--border-for-button-as-secondary, none)',
  borderForButtonAsSecondaryWhenHovered:
    'var(--border-for-button-as-secondary-when-hovered, none)',
  borderForButtonAsSecondaryWhenActive:
    'var(--border-for-button-as-secondary-when-active, none)',
  borderForCardWhenRaised: 'var(--border-for-card-when-raised, none)',
  borderForCollapsiblePanelHeaderIconWhenDisabled:
    'var(--border-for-collapsible-panel-header-icon-when-disabled, 1px solid var(--color-neutral))',
  borderForViewSwitcher: 'var(--border-for-view-switcher, none)',
  borderColorForInput: 'var(--border-color-for-input, hsl(0, 0%, 60%))',
  borderColorForInputWhenFocused:
    'var(--border-color-for-input-when-focused, #00b39e)',
  borderColorForInputWhenDisabled:
    'var(--border-color-for-input-when-disabled, #ccc)',
  borderColorForInputWhenReadonly:
    'var(--border-color-for-input-when-readonly, #ccc)',
  borderColorForInputWhenError:
    'var(--border-color-for-input-when-error, #e60050)',
  borderColorForInputWhenWarning:
    'var(--border-color-for-input-when-warning, #f16d0e)',
  borderColorForInputWhenHovered:
    'var(--border-color-for-input-when-hovered, #00b39e)',
  borderColorForTag: 'var(--border-color-for-tag, hsl(0, 0%, 60%))',
  borderColorForTagWarning: 'var(--border-color-for-tag-warning, #f16d0e)',
  borderColorForTagWhenFocused:
    'var(--border-color-for-tag-when-focused, #00b39e)',
  borderColorForTagWhenHovered:
    'var(--border-color-for-tag-when-hovered, #f16d0e)',
  borderColorForButtonAsIcon: 'var(--border-color-for-button-as-icon, #fff)',
  borderColorForButtonAsIconAsInfo:
    'var(--border-color-for-button-as-icon-as-info, #078cdf)',
  borderColorForButtonAsIconAsPrimary:
    'var(--border-color-for-button-as-icon-as-primary, #00b39e)',
  borderColorForButtonAsIconWhenDisabled:
    'var(--border-color-for-button-as-icon-when-disabled, #ccc)',
  borderColorForTableHeader: 'var(--border-color-for-table-header, #ccc)',
  borderColorForTableHeaderAsBottom:
    'var(--border-color-for-table-header-as-bottom, #213c45)',
  borderColorForTableManagerDroppableList:
    'var(--border-color-for-table-manager-droppable-list, hsl(0, 0%, 60%))',
  borderColorForCollapsiblePanelHeader:
    'var(--border-color-for-collapsible-panel-header, hsl(0, 0%, 60%))',
  borderColorForStampWhenError:
    'var(--border-color-for-stamp-when-error, #e60050)',
  borderColorForStampWhenWarning:
    'var(--border-color-for-stamp-when-warning, #f16d0e)',
  borderColorForStampAsPositive:
    'var(--border-color-for-stamp-as-positive, hsl(172.9608938547486, 100%, 40%))',
  borderColorForStampAsInformation:
    'var(--border-color-for-stamp-as-information, #078cdf)',
  borderColorForStampAsPrimary:
    'var(--border-color-for-stamp-as-primary, hsl(172.9608938547486, 100%, 25%))',
  borderColorForStampAsSecondary:
    'var(--border-color-for-stamp-as-secondary, hsl(0, 0%, 60%))',
  borderColorForLocalizedMultilineTextInputLabel:
    'var(--border-color-for-localized-multiline-text-input-label, #ccc)',
  borderColorForLocalizedMultilineTextInputLabelWhenReadonly:
    'var(--border-color-for-localized-multiline-text-input-label-when-readonly, #ccc)',
  borderColorForContentNotificationWhenError:
    'var(--border-color-for-content-notification-when-error, #e60050)',
  borderColorForContentNotificationWhenInfo:
    'var(--border-color-for-content-notification-when-info, #078cdf)',
  borderColorForContentNotificationWhenWarning:
    'var(--border-color-for-content-notification-when-warning, #f16d0e)',
  borderColorForContentNotificationWhenSuccess:
    'var(--border-color-for-content-notification-when-success, #00b39e)',
  borderColorForGroupHeadingSelectInputOptions:
    'var(--border-color-for-group-heading-select-input-options, #ccc)',
  borderColorForSelectInputMenu:
    'var(--border-color-for-select-input-menu, #00b39e)',
  borderColorForSelectInputWhenReadonly:
    'var(--border-color-for-select-input-when-readonly, #ccc)',
  borderColorForSelectInputMenuWhenWarning:
    'var(--border-color-for-select-input-menu-when-warning, #f16d0e)',
  borderColorForSelectInputMenuWhenError:
    'var(--border-color-for-select-input-menu-when-error, #e60050)',
  borderRadiusForButtonAsBig: 'var(--border-radius-for-button-as-big, 6px)',
  borderRadiusForButtonAsSmall: 'var(--border-radius-for-button-as-small, 4px)',
  borderRadiusForButtonAsIconAsBig:
    'var(--border-radius-for-button-as-icon-as-big, 6px)',
  borderRadiusForButtonAsIconAsMedium:
    'var(--border-radius-for-button-as-icon-as-medium, 4px)',
  borderRadiusForButtonAsIconAsSmall:
    'var(--border-radius-for-button-as-icon-as-small, 2px)',
  borderRadiusForInput: 'var(--border-radius-for-input, 6px)',
  borderRadiusForTag: 'var(--border-radius-for-tag, 2px)',
  borderRadiusForCard: 'var(--border-radius-for-card, 6px)',
  borderRadiusForTableManagerDroppableList:
    'var(--border-radius-for-table-manager-droppable-list, 6px)',
  borderRadiusForStamp: 'var(--border-radius-for-stamp, 2px)',
  borderRadiusForViewSwitcher: 'var(--border-radius-for-view-switcher, 6px)',
  borderRadiusForContentNotification:
    'var(--border-radius-for-content-notification, 0 var(--border-radius-6) var(--border-radius-6) 0)',
  borderRadiusForContentNotificationIcon:
    'var(--border-radius-for-content-notification-icon, var(--border-radius-6) 0 0 var(--border-radius-6))',
  borderWidthForInput: 'var(--border-width-for-input, 1px)',
  borderWidthForInputWhenWarning:
    'var(--border-width-for-input-when-warning, 1px)',
  borderWidthForInputWhenError: 'var(--border-width-for-input-when-error, 1px)',
  borderWidthForInputWhenFocused:
    'var(--border-width-for-input-when-focused, 1px)',
  borderWidthForTag: 'var(--border-width-for-tag, 1px)',
  borderWidthForSelectInput: 'var(--border-width-for-select-input, 1px)',
  borderWidthForContentNotificationIcon:
    'var(--border-width-for-content-notification-icon, 0px)',
  borderLeftWidthForContentNotification:
    'var(--border-left-width-for-content-notification, 1px)',
  boxShadowForDatetimeInputWhenHovered:
    'var(--box-shadow-for-datetime-input-when-hovered, inset 0 0 0 2px)',
  boxShadowForViewSwitcher:
    'var(--box-shadow-for-view-switcher, 0 1px 1px 0 rgba(0, 0, 0, 0.24), 0 -1px 1px 0 rgba(0, 0, 0, 0.12))',
  boxShadowForViewSwitcherWhenSelected:
    'var(--box-shadow-for-view-switcher-when-selected, inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25))',
  boxShadowForSelectInputWhenFocused:
    'var(--box-shadow-for-select-input-when-focused, inset 0 0 0 2px)',
  fontColorForText: 'var(--font-color-for-text, #1a1a1a)',
  fontColorForInput: 'var(--font-color-for-input, #1a1a1a)',
  fontColorForInputWhenDisabled:
    'var(--font-color-for-input-when-disabled, hsl(0, 0%, 60%))',
  fontColorForInputWhenError: 'var(--font-color-for-input-when-error, #e60050)',
  fontColorForInputWhenReadonly:
    'var(--font-color-for-input-when-readonly, hsl(0, 0%, 60%))',
  fontColorForInputWhenWarning:
    'var(--font-color-for-input-when-warning, #f16d0e)',
  fontColorForTag: 'var(--font-color-for-tag, #1a1a1a)',
  fontColorForTagRemoveIcon: 'var(--font-color-for-tag-remove-icon, #1a1a1a)',
  fontColorForTagDragIcon: 'var(--font-color-for-tag-drag-icon, #1a1a1a)',
  fontColorForTagRemoveIconWhenHovered:
    'var(--font-color-for-tag-remove-icon-when-hovered, #f16d0e)',
  fontColorForTagWhenDisabled:
    'var(--font-color-for-tag-when-disabled, hsl(0, 0%, 60%))',
  fontColorForTextWhenInverted:
    'var(--font-color-for-text-when-inverted, #fff)',
  fontColorForTableHeader: 'var(--font-color-for-table-header, #fff)',
  fontColorForLocalizedMultilineTextInputLabel:
    'var(--font-color-for-localized-multiline-text-input-label, hsl(0, 0%, 60%))',
  fontColorForViewSwitcher: 'var(--font-color-for-view-switcher, #1a1a1a)',
  fontColorForViewSwitcherWhenDisabled:
    'var(--font-color-for-view-switcher-when-disabled, hsl(0, 0%, 60%))',
  fontColorForViewSwitcherWhenSelected:
    'var(--font-color-for-view-switcher-when-selected, #1a1a1a)',
  fontColorForClearInputIcon: 'var(--font-color-for-clear-input-icon, #1a1a1a)',
  fontColorForClearInputIconWhenHovered:
    'var(--font-color-for-clear-input-icon-when-hovered, #f16d0e)',
  fontColorForContentNotification:
    'var(--font-color-for-content-notification, #1a1a1a)',
  fontColorForContentNotificationIconWhenError:
    'var(--font-color-for-content-notification-icon-when-error, #fff)',
  fontColorForContentNotificationIconWhenWarning:
    'var(--font-color-for-content-notification-icon-when-warning, #fff)',
  fontColorForContentNotificationIconWhenSuccess:
    'var(--font-color-for-content-notification-icon-when-success, #fff)',
  fontColorForContentNotificationIconWhenInfo:
    'var(--font-color-for-content-notification-icon-when-info, #fff)',
  fontColorForSearchInputIcon:
    'var(--font-color-for-search-input-icon, #1a1a1a)',
  fontColorForSearchInputIconWhenHovered:
    'var(--font-color-for-search-input-icon-when-hovered, #1a1a1a)',
  fontColorForSelectInputIcon:
    'var(--font-color-for-select-input-icon, #1a1a1a)',
  fontColorForSelectInputWhenError:
    'var(--font-color-for-select-input-when-error, hsl(0, 0%, 60%))',
  fontColorForSelectInputWhenWarning:
    'var(--font-color-for-select-input-when-warning, hsl(0, 0%, 60%))',
  fontColorForSelectInputIconWhenError:
    'var(--font-color-for-select-input-icon-when-error, #1a1a1a)',
  fontColorForSelectInputIconWhenWarning:
    'var(--font-color-for-select-input-icon-when-warning, #1a1a1a)',
  heightForButtonAsBig: 'var(--height-for-button-as-big, 32px)',
  heightForButtonAsSmall: 'var(--height-for-button-as-small, 24px)',
  heightForButtonAsIconAsBig: 'var(--height-for-button-as-icon-as-big, 32px)',
  heightForButtonAsIconAsMedium:
    'var(--height-for-button-as-icon-as-medium, 24px)',
  heightForButtonAsIconAsSmall:
    'var(--height-for-button-as-icon-as-small, 16px)',
  heightForInput: 'var(--height-for-input, 32px)',
  heightForViewSwitcher: 'var(--height-for-view-switcher, 32px)',
  heightForViewSwitcherWhenCondensed:
    'var(--height-for-view-switcher-when-condensed, 24px)',
  widthForAvatarAsMedium: 'var(--width-for-avatar-as-medium, 48px)',
  placeholderFontColorForInput:
    'var(--placeholder-font-color-for-input, hsl(0, 0%, 60%))',
  fontSizeForButton: 'var(--font-size-for-button, 1rem)',
  fontSizeForInput: 'var(--font-size-for-input, 1rem)',
  fontSizeForTextAsH1: 'var(--font-size-for-text-as-h-1, 2.4615rem)',
  fontSizeForTextAsH2: 'var(--font-size-for-text-as-h-2, 1.8462rem)',
  fontSizeForTextAsH3: 'var(--font-size-for-text-as-h-3, 1.5385rem)',
  fontSizeForTextAsH4: 'var(--font-size-for-text-as-h-4, 1.2308rem)',
  fontSizeForTextAsH5: 'var(--font-size-for-text-as-h-5, 1.0769rem)',
  fontSizeForTextAsBody: 'var(--font-size-for-text-as-body, 1rem)',
  fontSizeForTextAsDetail: 'var(--font-size-for-text-as-detail, 0.9231rem)',
  fontSizeForBody: 'var(--font-size-for-body, 13px)',
  fontSizeForLink: 'var(--font-size-for-link, 1rem)',
  fontSizeForStamp: 'var(--font-size-for-stamp, 1rem)',
  fontSizeForViewSwitcher: 'var(--font-size-for-view-switcher, 1rem)',
  fontSizeForTable: 'var(--font-size-for-table, 1rem)',
  fontSizeForAvatarAsSmall: 'var(--font-size-for-avatar-as-small, 1rem)',
  fontSizeForAvatarAsMedium: 'var(--font-size-for-avatar-as-medium, 1.5rem)',
  fontSizeForAvatarAsBig: 'var(--font-size-for-avatar-as-big, 3rem)',
  fontSizeForLocalizedMultilineTextInputLabel:
    'var(--font-size-for-localized-multiline-text-input-label, 0.9231rem)',
  fontSizeForContentNotification:
    'var(--font-size-for-content-notification, 1rem)',
  iconColorForDatetimeInputIcon:
    'var(--icon-color-for-datetime-input-icon, #1a1a1a)',
  iconColorForDatetimeInputIconWhenHovered:
    'var(--icon-color-for-datetime-input-icon-when-hovered, #f16d0e)',
  lineHeightForTextAsH1: 'var(--line-height-for-text-as-h-1, inherit)',
  lineHeightForTextAsH2: 'var(--line-height-for-text-as-h-2, inherit)',
  lineHeightForTextAsH3: 'var(--line-height-for-text-as-h-3, inherit)',
  lineHeightForTextAsH4: 'var(--line-height-for-text-as-h-4, inherit)',
  lineHeightForTextAsH5: 'var(--line-height-for-text-as-h-5, inherit)',
  lineHeightForTextAsBody: 'var(--line-height-for-text-as-body, inherit)',
  lineHeightForTextAsDetail: 'var(--line-height-for-text-as-detail, inherit)',
  fontWeightForTextAsH1: 'var(--font-weight-for-text-as-h-1, 300)',
  fontWeightForTextAsH2: 'var(--font-weight-for-text-as-h-2, 300)',
  fontWeightForTextAsH3: 'var(--font-weight-for-text-as-h-3, 300)',
  fontWeightForTextAsH4: 'var(--font-weight-for-text-as-h-4, 400)',
  fontWeightForTextAsH5: 'var(--font-weight-for-text-as-h-5, 400)',
  fontWeightForTextAsBody: 'var(--font-weight-for-text-as-body, 400)',
  fontWeightForTextAsDetail: 'var(--font-weight-for-text-as-detail, 400)',
  fontWeightForButton: 'var(--font-weight-for-button, 400)',
  fontWeightForTableHeader: 'var(--font-weight-for-table-header, 400)',
  marginForTableHeader: 'var(--margin-for-table-header, 8px)',
  marginForTableAsCondensed: 'var(--margin-for-table-as-condensed, 8px)',
  marginForViewSwitcherIcon:
    'var(--margin-for-view-switcher-icon, 0 var(--spacing-10) 0 0)',
  marginForGroupHeadingSelectInputOptions:
    'var(--margin-for-group-heading-select-input-options, 4px)',
  marginForSelectInputIcon: 'var(--margin-for-select-input-icon, 4px)',
  marginLeftForSelectInputIcon:
    'var(--margin-left-for-select-input-icon, inherit)',
  paddingForStamp:
    'var(--padding-for-stamp, var(--spacing-10) var(--spacing-20))',
  paddingForStampAsCondensed:
    'var(--padding-for-stamp-as-condensed, 1px var(--spacing-10))',
  paddingForTag: 'var(--padding-for-tag, 5px var(--spacing-20))',
  paddingForTableHeader: 'var(--padding-for-table-header, 16px)',
  paddingForTableHeaderAsCondensed:
    'var(--padding-for-table-header-as-condensed, 8px)',
  paddingForTableCell: 'var(--padding-for-table-cell, 16px)',
  paddingForTableCellAsCondensed:
    'var(--padding-for-table-cell-as-condensed, 8px)',
  paddingForTableManagerDroppableList:
    'var(--padding-for-table-manager-droppable-list, 8px)',
  paddingForTableManagerSettingsPanel:
    'var(--padding-for-table-manager-settings-panel, 16px)',
  paddingForTableManagerDraggableTag:
    'var(--padding-for-table-manager-draggable-tag, 4px)',
  paddingForCollapsiblePanelHeader:
    'var(--padding-for-collapsible-panel-header, var(--spacing-20) var(--spacing-30))',
  paddingForCollapsiblePanelHeaderAsCondensed:
    'var(--padding-for-collapsible-panel-header-as-condensed, 8px)',
  paddingForCollapsiblePanelSectionWrapper:
    'var(--padding-for-collapsible-panel-section-wrapper, 16px)',
  paddingForCollapsiblePanelSectionWrapperAsCondensed:
    'var(--padding-for-collapsible-panel-section-wrapper-as-condensed, 8px)',
  paddingForCollapsiblePanelSectionDescription:
    'var(--padding-for-collapsible-panel-section-description, 0 0 var(--spacing-50))',
  paddingForCollapsiblePanelSectionDescriptionAsCondensed:
    'var(--padding-for-collapsible-panel-section-description-as-condensed, 0 0 var(--spacing-30))',
  paddingForInput: 'var(--padding-for-input, 8px)',
  paddingForMultilineInput:
    'var(--padding-for-multiline-input, var(--spacing-10) var(--spacing-20))',
  paddingForLocalizedRichTextInputLabel:
    'var(--padding-for-localized-rich-text-input-label, 0 var(--spacing-20))',
  paddingForLocalizedMultilineTextInputLabel:
    'var(--padding-for-localized-multiline-text-input-label, 0 var(--spacing-20))',
  paddingForTagRemoveIcon:
    'var(--padding-for-tag-remove-icon, 0 var(--spacing-10))',
  paddingForTooltip:
    'var(--padding-for-tooltip, var(--spacing-10) var(--spacing-20))',
  paddingForViewSwitcher:
    'var(--padding-for-view-switcher, 0 var(--spacing-30) 0 var(--spacing-30))',
  paddingForViewSwitcherWhenCondensed:
    'var(--padding-for-view-switcher-when-condensed, 0 var(--spacing-20) 0 var(--spacing-20))',
  paddingForContentNotification:
    'var(--padding-for-content-notification, var(--spacing-20))',
  paddingForContentNotificationIcon:
    'var(--padding-for-content-notification-icon, var(--spacing-20) var(--spacing-30))',
  paddingLeftForSelectInputOptions:
    'var(--padding-left-for-select-input-options, 8px)',
  paddingRightForSelectInputOptions:
    'var(--padding-right-for-select-input-options, 8px)',
  paddingTopForSelectInputOptions:
    'var(--padding-top-for-select-input-options, 4px)',
  paddingBottomForSelectInputOptions:
    'var(--padding-bottom-for-select-input-options, 4px)',
  paddingForGroupHeadingSelectInputOptions:
    'var(--padding-for-group-heading-select-input-options, 8px)',
  paddingForSelectInputMenu: 'var(--padding-for-select-input-menu, inherit)',
  shadowForButton:
    'var(--shadow-for-button, 0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24))',
  shadowForButtonWhenFocused:
    'var(--shadow-for-button-when-focused, 0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24))',
  shadowForButtonWhenHovered:
    'var(--shadow-for-button-when-hovered, 0 1px 9.5px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.24))',
  shadowForButtonWhenActive:
    'var(--shadow-for-button-when-active, inset 0 -1px 3px 0 rgba(0, 0, 0, 0.1), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.2), inset 0 1px 1.5px 0 rgba(0, 0, 0, 0.25))',
  shadowForButtonWhenDisabled:
    'var(--shadow-for-button-when-disabled, 0 0 0 1px var(--color-neutral) inset)',
  shadowBoxTagWhenHovered:
    'var(--shadow-box-tag-when-hovered, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  shadowForCardWhenRaised:
    'var(--shadow-for-card-when-raised, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  shadowForInput: 'var(--shadow-for-input, none)',
  shadowForInputWhenFocused:
    'var(--shadow-for-input-when-focused, inset 0 0 0 2px var(--color-primary))',
  shadowForInputWhenError: 'var(--shadow-for-input-when-error, none)',
  shadowForInputWhenWarning: 'var(--shadow-for-input-when-warning, none)',
  shadowForTooltip:
    'var(--shadow-for-tooltip, 0 2px 2px rgba(0, 0, 0, 0.24), 0 1px 4.75px rgba(0, 0, 0, 0.12))',
  shadowForSelectInputMenu:
    'var(--shadow-for-select-input-menu, 0 -1px 1.5px 0 rgba(0, 0, 0, 0.12), 0 1px 1px 0 rgba(0, 0, 0, 0.24))',
  fontSizeM: 'var(--font-size-m, 1rem)',
  bigButtonHeight: 'var(--big-button-height, 32px)',
  smallButtonHeight: 'var(--small-button-height, 24px)',
  sizeHeightInput: 'var(--size-height-input, 32px)',
  fontFamilyDefault: "var(--font-family-default, 'Open Sans', sans-serif)",
  fontSizeDefault: 'var(--font-size-default, 1rem)',
  fontSizeSmall: 'var(--font-size-small, 0.9231rem)',
  shadowBoxTagHover:
    'var(--shadow-box-tag-hover, 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24))',
  sizeHeightTag: 'var(--size-height-tag, 26px)',
  standardInputHeight: 'var(--standard-input-height, 32px)',
} as const;

export default designTokens;
