---
rules:
    # ui-kit is a mapped module, so it will not be found
    # We exclude it from the checks
    'import/no-unresolved': [2, { ignore: ['^ui-kit$'] }]
    # ui-kit is a mapped module, so it will not be found
    # settting ignorePackages will disable the extension warning for it.
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
      },
    ] 