// This file is auto-generated using the 'generate-icon-exports.js' script
// so any changes made to this file manually will be lost the next time the
// script is executed
import withSizeProp from './with-size-prop';
import withThemeProp from './with-theme-prop';
import OrigAddBold from './svg/add-bold.react.svg';
import OrigAdd from './svg/add.react.svg';
import OrigAngleDown from './svg/angle-down.react.svg';
import OrigAngleLeft from './svg/angle-left.react.svg';
import OrigAngleRight from './svg/angle-right.react.svg';
import OrigAngleThinLeft from './svg/angle-thin-left.react.svg';
import OrigAngleThinRight from './svg/angle-thin-right.react.svg';
import OrigAngleUp from './svg/angle-up.react.svg';
import OrigArrowDown from './svg/arrow-down.react.svg';
import OrigArrowLeft from './svg/arrow-left.react.svg';
import OrigArrowLongDown from './svg/arrow-long-down.react.svg';
import OrigArrowRight from './svg/arrow-right.react.svg';
import OrigArrowTriangleDown from './svg/arrow-triangle-down.react.svg';
import OrigArrowTriangleUp from './svg/arrow-triangle-up.react.svg';
import OrigArrowUp from './svg/arrow-up.react.svg';
import OrigArrows from './svg/arrows.react.svg';
import OrigBack from './svg/back.react.svg';
import OrigBidirectionalArrow from './svg/bidirectional-arrow.react.svg';
import OrigBox from './svg/box.react.svg';
import OrigBrain from './svg/brain.react.svg';
import OrigCalendar from './svg/calendar.react.svg';
import OrigCamera from './svg/camera.react.svg';
import OrigCaretDown from './svg/caret-down.react.svg';
import OrigCaretUp from './svg/caret-up.react.svg';
import OrigCart from './svg/cart.react.svg';
import OrigChainBroken from './svg/chain-broken.react.svg';
import OrigChain from './svg/chain.react.svg';
import OrigCheckActive from './svg/check-active.react.svg';
import OrigCheckInactive from './svg/check-inactive.react.svg';
import OrigClipboard from './svg/clipboard.react.svg';
import OrigClock from './svg/clock.react.svg';
import OrigCloseBold from './svg/close-bold.react.svg';
import OrigClose from './svg/close.react.svg';
import OrigCodeView from './svg/code-view.react.svg';
import OrigCoins from './svg/coins.react.svg';
import OrigColumns from './svg/columns.react.svg';
import OrigConnectedSquare from './svg/connected-square.react.svg';
import OrigConnectedTriangle from './svg/connected-triangle.react.svg';
import OrigCopy from './svg/copy.react.svg';
import OrigCube from './svg/cube.react.svg';
import OrigCubes from './svg/cubes.react.svg';
import OrigDeleteFilled from './svg/delete-filled.react.svg';
import OrigDelete from './svg/delete.react.svg';
import OrigDone from './svg/done.react.svg';
import OrigDot from './svg/dot.react.svg';
import OrigDownload from './svg/download.react.svg';
import OrigDragDrop from './svg/drag-drop.react.svg';
import OrigDrag from './svg/drag.react.svg';
import OrigEdit from './svg/edit.react.svg';
import OrigError from './svg/error.react.svg';
import OrigExpand from './svg/expand.react.svg';
import OrigExport from './svg/export.react.svg';
import OrigFilter from './svg/filter.react.svg';
import OrigFlagFullfiled from './svg/flag-fullfiled.react.svg';
import OrigFlag from './svg/flag.react.svg';
import OrigFlame from './svg/flame.react.svg';
import OrigGear from './svg/gear.react.svg';
import OrigGraph from './svg/graph.react.svg';
import OrigGrid from './svg/grid.react.svg';
import OrigHeart from './svg/heart.react.svg';
import OrigImport from './svg/import.react.svg';
import OrigInfo from './svg/info.react.svg';
import OrigInformation from './svg/information.react.svg';
import OrigList from './svg/list.react.svg';
import OrigLogout from './svg/logout.react.svg';
import OrigMail from './svg/mail.react.svg';
import OrigMinimize from './svg/minimize.react.svg';
import OrigNestedView from './svg/nested-view.react.svg';
import OrigPages from './svg/pages.react.svg';
import OrigPaperBillInverted from './svg/paper-bill-inverted.react.svg';
import OrigPaperclip from './svg/paperclip.react.svg';
import OrigPinActive from './svg/pin-active.react.svg';
import OrigPin from './svg/pin.react.svg';
import OrigPlugin from './svg/plugin.react.svg';
import OrigRefresh from './svg/refresh.react.svg';
import OrigRestore from './svg/restore.react.svg';
import OrigRevert from './svg/revert.react.svg';
import OrigReview from './svg/review.react.svg';
import OrigRocket from './svg/rocket.react.svg';
import OrigScreenGear from './svg/screen-gear.react.svg';
import OrigScreenUser from './svg/screen-user.react.svg';
import OrigSearch from './svg/search.react.svg';
import OrigSorting from './svg/sorting.react.svg';
import OrigSpeedometer from './svg/speedometer.react.svg';
import OrigSplit from './svg/split.react.svg';
import OrigStar from './svg/star.react.svg';
import OrigSuccess from './svg/success.react.svg';
import OrigSupport from './svg/support.react.svg';
import OrigSwitcher from './svg/switcher.react.svg';
import OrigTable from './svg/table.react.svg';
import OrigTagMulti from './svg/tag-multi.react.svg';
import OrigTagStacked from './svg/tag-stacked.react.svg';
import OrigTag from './svg/tag.react.svg';
import OrigTreeStructure from './svg/tree-structure.react.svg';
import OrigTruck from './svg/truck.react.svg';
import OrigUserFilled from './svg/user-filled.react.svg';
import OrigUserLinear from './svg/user-linear.react.svg';
import OrigVerified from './svg/verified.react.svg';
import OrigWarning from './svg/warning.react.svg';
import OrigWorld from './svg/world.react.svg';

export const AddBold = withThemeProp(withSizeProp(OrigAddBold));
AddBold.displayName = 'AddBoldIcon';
export const Add = withThemeProp(withSizeProp(OrigAdd));
Add.displayName = 'AddIcon';
export const AngleDown = withThemeProp(withSizeProp(OrigAngleDown));
AngleDown.displayName = 'AngleDownIcon';
export const AngleLeft = withThemeProp(withSizeProp(OrigAngleLeft));
AngleLeft.displayName = 'AngleLeftIcon';
export const AngleRight = withThemeProp(withSizeProp(OrigAngleRight));
AngleRight.displayName = 'AngleRightIcon';
export const AngleThinLeft = withThemeProp(withSizeProp(OrigAngleThinLeft));
AngleThinLeft.displayName = 'AngleThinLeftIcon';
export const AngleThinRight = withThemeProp(withSizeProp(OrigAngleThinRight));
AngleThinRight.displayName = 'AngleThinRightIcon';
export const AngleUp = withThemeProp(withSizeProp(OrigAngleUp));
AngleUp.displayName = 'AngleUpIcon';
export const ArrowDown = withThemeProp(withSizeProp(OrigArrowDown));
ArrowDown.displayName = 'ArrowDownIcon';
export const ArrowLeft = withThemeProp(withSizeProp(OrigArrowLeft));
ArrowLeft.displayName = 'ArrowLeftIcon';
export const ArrowLongDown = withThemeProp(withSizeProp(OrigArrowLongDown));
ArrowLongDown.displayName = 'ArrowLongDownIcon';
export const ArrowRight = withThemeProp(withSizeProp(OrigArrowRight));
ArrowRight.displayName = 'ArrowRightIcon';
export const ArrowTriangleDown = withThemeProp(
  withSizeProp(OrigArrowTriangleDown)
);
ArrowTriangleDown.displayName = 'ArrowTriangleDownIcon';
export const ArrowTriangleUp = withThemeProp(withSizeProp(OrigArrowTriangleUp));
ArrowTriangleUp.displayName = 'ArrowTriangleUpIcon';
export const ArrowUp = withThemeProp(withSizeProp(OrigArrowUp));
ArrowUp.displayName = 'ArrowUpIcon';
export const Arrows = withThemeProp(withSizeProp(OrigArrows));
Arrows.displayName = 'ArrowsIcon';
export const Back = withThemeProp(withSizeProp(OrigBack));
Back.displayName = 'BackIcon';
export const BidirectionalArrow = withThemeProp(
  withSizeProp(OrigBidirectionalArrow)
);
BidirectionalArrow.displayName = 'BidirectionalArrowIcon';
export const Box = withThemeProp(withSizeProp(OrigBox));
Box.displayName = 'BoxIcon';
export const Brain = withThemeProp(withSizeProp(OrigBrain));
Brain.displayName = 'BrainIcon';
export const Calendar = withThemeProp(withSizeProp(OrigCalendar));
Calendar.displayName = 'CalendarIcon';
export const Camera = withThemeProp(withSizeProp(OrigCamera));
Camera.displayName = 'CameraIcon';
export const CaretDown = withThemeProp(withSizeProp(OrigCaretDown));
CaretDown.displayName = 'CaretDownIcon';
export const CaretUp = withThemeProp(withSizeProp(OrigCaretUp));
CaretUp.displayName = 'CaretUpIcon';
export const Cart = withThemeProp(withSizeProp(OrigCart));
Cart.displayName = 'CartIcon';
export const ChainBroken = withThemeProp(withSizeProp(OrigChainBroken));
ChainBroken.displayName = 'ChainBrokenIcon';
export const Chain = withThemeProp(withSizeProp(OrigChain));
Chain.displayName = 'ChainIcon';
export const CheckActive = withThemeProp(withSizeProp(OrigCheckActive));
CheckActive.displayName = 'CheckActiveIcon';
export const CheckInactive = withThemeProp(withSizeProp(OrigCheckInactive));
CheckInactive.displayName = 'CheckInactiveIcon';
export const Clipboard = withThemeProp(withSizeProp(OrigClipboard));
Clipboard.displayName = 'ClipboardIcon';
export const Clock = withThemeProp(withSizeProp(OrigClock));
Clock.displayName = 'ClockIcon';
export const CloseBold = withThemeProp(withSizeProp(OrigCloseBold));
CloseBold.displayName = 'CloseBoldIcon';
export const Close = withThemeProp(withSizeProp(OrigClose));
Close.displayName = 'CloseIcon';
export const CodeView = withThemeProp(withSizeProp(OrigCodeView));
CodeView.displayName = 'CodeViewIcon';
export const Coins = withThemeProp(withSizeProp(OrigCoins));
Coins.displayName = 'CoinsIcon';
export const Columns = withThemeProp(withSizeProp(OrigColumns));
Columns.displayName = 'ColumnsIcon';
export const ConnectedSquare = withThemeProp(withSizeProp(OrigConnectedSquare));
ConnectedSquare.displayName = 'ConnectedSquareIcon';
export const ConnectedTriangle = withThemeProp(
  withSizeProp(OrigConnectedTriangle)
);
ConnectedTriangle.displayName = 'ConnectedTriangleIcon';
export const Copy = withThemeProp(withSizeProp(OrigCopy));
Copy.displayName = 'CopyIcon';
export const Cube = withThemeProp(withSizeProp(OrigCube));
Cube.displayName = 'CubeIcon';
export const Cubes = withThemeProp(withSizeProp(OrigCubes));
Cubes.displayName = 'CubesIcon';
export const DeleteFilled = withThemeProp(withSizeProp(OrigDeleteFilled));
DeleteFilled.displayName = 'DeleteFilledIcon';
export const Delete = withThemeProp(withSizeProp(OrigDelete));
Delete.displayName = 'DeleteIcon';
export const Done = withThemeProp(withSizeProp(OrigDone));
Done.displayName = 'DoneIcon';
export const Dot = withThemeProp(withSizeProp(OrigDot));
Dot.displayName = 'DotIcon';
export const Download = withThemeProp(withSizeProp(OrigDownload));
Download.displayName = 'DownloadIcon';
export const DragDrop = withThemeProp(withSizeProp(OrigDragDrop));
DragDrop.displayName = 'DragDropIcon';
export const Drag = withThemeProp(withSizeProp(OrigDrag));
Drag.displayName = 'DragIcon';
export const Edit = withThemeProp(withSizeProp(OrigEdit));
Edit.displayName = 'EditIcon';
export const Error = withThemeProp(withSizeProp(OrigError));
Error.displayName = 'ErrorIcon';
export const Expand = withThemeProp(withSizeProp(OrigExpand));
Expand.displayName = 'ExpandIcon';
export const Export = withThemeProp(withSizeProp(OrigExport));
Export.displayName = 'ExportIcon';
export const Filter = withThemeProp(withSizeProp(OrigFilter));
Filter.displayName = 'FilterIcon';
export const FlagFullfiled = withThemeProp(withSizeProp(OrigFlagFullfiled));
FlagFullfiled.displayName = 'FlagFullfiledIcon';
export const Flag = withThemeProp(withSizeProp(OrigFlag));
Flag.displayName = 'FlagIcon';
export const Flame = withThemeProp(withSizeProp(OrigFlame));
Flame.displayName = 'FlameIcon';
export const Gear = withThemeProp(withSizeProp(OrigGear));
Gear.displayName = 'GearIcon';
export const Graph = withThemeProp(withSizeProp(OrigGraph));
Graph.displayName = 'GraphIcon';
export const Grid = withThemeProp(withSizeProp(OrigGrid));
Grid.displayName = 'GridIcon';
export const Heart = withThemeProp(withSizeProp(OrigHeart));
Heart.displayName = 'HeartIcon';
export const Import = withThemeProp(withSizeProp(OrigImport));
Import.displayName = 'ImportIcon';
export const Info = withThemeProp(withSizeProp(OrigInfo));
Info.displayName = 'InfoIcon';
export const Information = withThemeProp(withSizeProp(OrigInformation));
Information.displayName = 'InformationIcon';
export const List = withThemeProp(withSizeProp(OrigList));
List.displayName = 'ListIcon';
export const Logout = withThemeProp(withSizeProp(OrigLogout));
Logout.displayName = 'LogoutIcon';
export const Mail = withThemeProp(withSizeProp(OrigMail));
Mail.displayName = 'MailIcon';
export const Minimize = withThemeProp(withSizeProp(OrigMinimize));
Minimize.displayName = 'MinimizeIcon';
export const NestedView = withThemeProp(withSizeProp(OrigNestedView));
NestedView.displayName = 'NestedViewIcon';
export const Pages = withThemeProp(withSizeProp(OrigPages));
Pages.displayName = 'PagesIcon';
export const PaperBillInverted = withThemeProp(
  withSizeProp(OrigPaperBillInverted)
);
PaperBillInverted.displayName = 'PaperBillInvertedIcon';
export const Paperclip = withThemeProp(withSizeProp(OrigPaperclip));
Paperclip.displayName = 'PaperclipIcon';
export const PinActive = withThemeProp(withSizeProp(OrigPinActive));
PinActive.displayName = 'PinActiveIcon';
export const Pin = withThemeProp(withSizeProp(OrigPin));
Pin.displayName = 'PinIcon';
export const Plugin = withThemeProp(withSizeProp(OrigPlugin));
Plugin.displayName = 'PluginIcon';
export const Refresh = withThemeProp(withSizeProp(OrigRefresh));
Refresh.displayName = 'RefreshIcon';
export const Restore = withThemeProp(withSizeProp(OrigRestore));
Restore.displayName = 'RestoreIcon';
export const Revert = withThemeProp(withSizeProp(OrigRevert));
Revert.displayName = 'RevertIcon';
export const Review = withThemeProp(withSizeProp(OrigReview));
Review.displayName = 'ReviewIcon';
export const Rocket = withThemeProp(withSizeProp(OrigRocket));
Rocket.displayName = 'RocketIcon';
export const ScreenGear = withThemeProp(withSizeProp(OrigScreenGear));
ScreenGear.displayName = 'ScreenGearIcon';
export const ScreenUser = withThemeProp(withSizeProp(OrigScreenUser));
ScreenUser.displayName = 'ScreenUserIcon';
export const Search = withThemeProp(withSizeProp(OrigSearch));
Search.displayName = 'SearchIcon';
export const Sorting = withThemeProp(withSizeProp(OrigSorting));
Sorting.displayName = 'SortingIcon';
export const Speedometer = withThemeProp(withSizeProp(OrigSpeedometer));
Speedometer.displayName = 'SpeedometerIcon';
export const Split = withThemeProp(withSizeProp(OrigSplit));
Split.displayName = 'SplitIcon';
export const Star = withThemeProp(withSizeProp(OrigStar));
Star.displayName = 'StarIcon';
export const Success = withThemeProp(withSizeProp(OrigSuccess));
Success.displayName = 'SuccessIcon';
export const Support = withThemeProp(withSizeProp(OrigSupport));
Support.displayName = 'SupportIcon';
export const Switcher = withThemeProp(withSizeProp(OrigSwitcher));
Switcher.displayName = 'SwitcherIcon';
export const Table = withThemeProp(withSizeProp(OrigTable));
Table.displayName = 'TableIcon';
export const TagMulti = withThemeProp(withSizeProp(OrigTagMulti));
TagMulti.displayName = 'TagMultiIcon';
export const TagStacked = withThemeProp(withSizeProp(OrigTagStacked));
TagStacked.displayName = 'TagStackedIcon';
export const Tag = withThemeProp(withSizeProp(OrigTag));
Tag.displayName = 'TagIcon';
export const TreeStructure = withThemeProp(withSizeProp(OrigTreeStructure));
TreeStructure.displayName = 'TreeStructureIcon';
export const Truck = withThemeProp(withSizeProp(OrigTruck));
Truck.displayName = 'TruckIcon';
export const UserFilled = withThemeProp(withSizeProp(OrigUserFilled));
UserFilled.displayName = 'UserFilledIcon';
export const UserLinear = withThemeProp(withSizeProp(OrigUserLinear));
UserLinear.displayName = 'UserLinearIcon';
export const Verified = withThemeProp(withSizeProp(OrigVerified));
Verified.displayName = 'VerifiedIcon';
export const Warning = withThemeProp(withSizeProp(OrigWarning));
Warning.displayName = 'WarningIcon';
export const World = withThemeProp(withSizeProp(OrigWorld));
World.displayName = 'WorldIcon';
